### ISSUE TITLE
代理端口设置

### ISSUE THREAD

**Issue by yueliuLEE** [KaringX/karing#10]
大佬,客户端怎么固定代理端口,现在的情况是设置完代理端口后,下一次重新启动就又回到默认的代理端口

**Comment by KaringX** [comment]
哪个端口？

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yueliuLEE ***@***.***>
发送时间: Sunday, January 21, 2024 11:43:58 PM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KaringX/karing] 代理端口设置 (Issue #10)


大佬,客户端怎么固定代理端口,现在的情况是设置完代理端口后,下一次重新启动就又回到默认的代理端口

―

**Comment by KaringX** [comment]
端口设置完毕,要返回到主屏才会保存
