### ISSUE TITLE
win11无法启动安装程序或者压缩包内的程序

### ISSUE THREAD

**Issue by dong-dong6** [KaringX/karing#102]
win11无法启动安装程序或者压缩包内的程序，我另一台win10可以启动与安装，这是我的问题还是什么情况

> 版本	Windows 11 专业工作站版
版本	23H2
安装日期	‎2024/‎4/‎14
操作系统版本	22631.3593
体验	Windows Feature Experience Pack 1000.22700.1003.0

**Comment by GooRingX** [comment]
重新下载试试

**Comment by dong-dong6** [comment]
我尝试过了，依然是没有任何反应，我也换过好几个版本了

**Comment by dong-dong6** [comment]
以管理员身份运行也是没有任何反应

**Comment by GooRingX** [comment]
下载 Procmon.exe, 录制一下karing.exe 进程启动信息

**Comment by dong-dong6** [comment]
我发现不止你这一个软件会出现这个情况，我在`[微软社区](https://answers.microsoft.com/zh-hans/windows/forum/all/windows11%E5%8F%8C%E5%87%BB%E6%97%A0%E5%8F%8D/4a4f949a-9eef-43ec-8b06-19cef76a4787)`获得了有用的答复，通过新建管理员用户修复了这个问题，抱歉
