### ISSUE TITLE
Please enable to add additional configs to the existing profiles 

### ISSUE THREAD

**Issue by javadgh6** [KaringX/karing#103]
Thank you for your nice application. It works like a charm.

In the current version every time we have to add configs as new profiles. I think it would be best to enable to add configs to the existing profiles. 
Please also enable the app to get remark for the profile automatically.

**Comment by GooRingX** [comment]
1. you can merge you local profiles in [Profiles]
2. remark is automatically setted from url fragment, if it doest work, send developer the profile link

**Comment by javadgh6** [comment]
I find it !!!! 
![Uploading Untitled.jpg…]()
