### ISSUE TITLE
According to the open-source license of sing-box, please open source your project.

### ISSUE THREAD

**Issue by leic4u** [KaringX/karing#105]
Sing-box is open-source based on GPLv3, which asks the derivative projects must be open-source.

Please see [license of sing-box](https://github.com/SagerNet/sing-box/blob/dev-next/LICENSE#L4-L5) and [GNU GPLv3.0 license](https://www.gnu.org/licenses/gpl-3.0.html).

---

**Please don't close this issue before your project is open-source.**

**Comment by GooRingX** [comment]
1. Open source work is currently in progress
2. issue is only for feedback on app issues.

**Comment by helpmebro911** [comment]
?
