### ISSUE TITLE
support for wiregard

### ISSUE THREAD

**Issue by javadgh6** [KaringX/karing#106]
Could you please enable support for this type of configs
sn://wg?eNpjYmBgMDQz0jM0tdQztDTVs9xxmxkoYg4UMdMz0DPSN960NtvFwiXJojzfJFPb0F_f1Dw7wzUnKT_Xq9QixCTZxTfVw8fZtCrT37PMI9B2bVJuhL-ztpuhW4Wrr5tlSmWmt5GHqb5hcGhJlYeBV2lYvqlhhlF5QFp6Zb5tIwMrA0MjI9AJ4Y5BAbrOIQobGxsBWsopdw

**Comment by misagh72** [comment]
wireguard already supported. use this format
wireguard://
https://github.com/KaringX/karing/releases/tag/v1.0.23-261
but the link u send only work in the specific app

**Comment by GooRingX** [comment]
no plan to support sn://
