### ISSUE TITLE
Proxy mode working? 

### ISSUE THREAD

**Issue by Amimomo1** [KaringX/karing#107]
I didn't find proxy mode.
I need it to use this as socks proxy with rethink firewall.
Can u help pls?

**Comment by GooRingX** [comment]
only pc version support proxy mode

**Comment by Amimomo1** [comment]
> only pc version support proxy mode

Please add proxy mode for Android.
Is very needed.
Thanks.

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-281
