### ISSUE TITLE
请开源你的项目

### ISSUE THREAD

**Issue by PuerNya** [KaringX/karing#11]
根据 sing-box 开源协议
https://github.com/SagerNet/sing-box/blob/bb7b29923a72ce5c56fe00f56ccd9b469313e260/LICENSE#L1-L17
该项目的代码开源基于 GPLv3，且添加了附加条款
https://github.com/SagerNet/sing-box/blob/bb7b29923a72ce5c56fe00f56ccd9b469313e260/LICENSE#L16-L17
请仔细阅读

**Comment by KaringX** [comment]
Related projects will be gradually open sourced after the app is stabilized.

**Comment by leic4u** [comment]
有开源的时间计划吗？

**Comment by goddaneel** [comment]
似乎没有合适的开源许可证
