### ISSUE TITLE
Noise parameters for wireguard (specially for warp)

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#111]
If you watch warp configs of warp in Hiddify app, you can see these parameters:
      "fake_packets": 
      "fake_packets_size": 
      "fake_packets_delay": 

Source code can be found from here:
https://github.com/hiddify/hiddify-core

I hope your app could support this, like fragment settings that you added before.

Regards

**Comment by Mimiiiir** [comment]
also add reserved parameter

**Comment by GooRingX** [comment]
> also add reserved parameter

Please provide test link

**Comment by GooRingX** [comment]
> And also this one: https://github.com/NiREvil/vless/blob/main/warpONwarp/2.json

sing-box json is supported, v2ray format needs to be provided
