### ISSUE TITLE
add ntp client

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#112]
It's use cases are environments that system time cannot be set to the correct time. One such environment is an old phone whose Timezone data is outdated, one needs to manually adjust his clock which results in some protocols (like shadowsocks) to stop working. By using the ntp client, correct time can be used for the proxy configurations and it can improve usability in the aforementioned scenarios.

All codes and details you may need:

xchacha20-poly1305/husi#107

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.23-266
