### ISSUE TITLE
Essential features

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#113]
First l, please watch this config:
https://github.com/abbasdvd3/clash/blob/main/se.json

For some vless or vmess or trojan configs (tls ws), Can these sections be imported ? 

        "tls_tricks": {
          "mixedcase_sni": true,
          "padding_mode": "random",
          "padding_size": "1-1500"
        }

All above options of tls ws configs can be found in Hiddify core. (also provide to have "**padding_mode**" & "**padding_size**" in **fragment** menu" of Karing

Source code:
https://github.com/hiddify/hiddify-core

**Comment by GooRingX** [comment]
mixedcase_sni  : Settings - TLS- Enable Mixed SNI

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.25-300

**Comment by GooRingX** [comment]
> Thank you But you've missed "custom MTU"

Settings-TUN-MTU

**Comment by GooRingX** [comment]
> @GooRingX and also CA certificate

Settings-TLS -Ignore Certificate Errors
