### ISSUE TITLE
Public wifi problem and solution

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#118]
As an android user,When we connect to public wifi, we have to disconnect karing to skip ads or login to wifi (user and password) then connect to karing again! Here's a solution by adding these in tun section of singbox comfigs:

      "exclude_package": [
          "com.android.captiveportallogin",
"com.google.android.overlay.modules.captiveportallogin.forframework"
     ],

Those mentioned app are used for login android web pages of public wifi connections in android phones.

"exclude_package" is found in documentation of singbox core.

I hope you would add these two apps in exclude_package to bypass them whenever we want to login or skip public wifi connections

Regards

**Comment by GooRingX** [comment]
Per-App Proxy - disable [Whitelist Mode]
