### ISSUE TITLE
请支持DNS DoH/DoT + ECH

### ISSUE THREAD

**Issue by zptan** [KaringX/karing#12]
DNS地址直接写了IP而不是域名(比如)，我在手机与PC上测试过，使用IP是不支持ECH的，在PC上测试过使用域名支持DoH/DoT + ECH，所以建议使用域名，比如Google DNS应该是 https://dns.google/dns-query

或者可以支持自定义DNS地址也可以，能支持DoH/DoT + ECH就好

这里提供测试DoH/DoT + ECH的网站
- https://tls-ech.dev
- https://www.cloudflare.com/ssl/encrypted-sni/

**Comment by KaringX** [comment]
dot: 1.0.15.134
ech: Just add a proxy server that supports ech
