### ISSUE TITLE
Cannot Add local proxy as a server/ front proxy

### ISSUE THREAD

**Issue by Economic-PunPun** [KaringX/karing#128]
I wanna add my local proxy socks://127.0.0.1:8086 as a server and use it in the front proxy section or connect using karing to use diversion rules but the app gives me an error (running on Windows)
Error Message:
```
launch process C:\Program Files\Karing\karingService.exe failed: process exit:1:2024/06/09 17:28:57 [31mFATAL[0m[0000]  export.go:51 : create service: default detour not found: no name:0
```

**Comment by GooRingX** [comment]
Please provide:
karing version number and reproduction process. If personal private configuration information is involved, please send the configuration information to the administrator: https://t.me/KaringApp

**Comment by GooRingX** [comment]
update to 1.0.24.285

**Comment by Economic-PunPun** [comment]
Thanks. Updated to 1.0.24.285 and it's been fixed.
