### ISSUE TITLE
Some existing problems and suggestions for improvement

### ISSUE THREAD

**Issue by HoangNguyen19032002** [KaringX/karing#13]
in the latest version for Android 197. when changing the server in the connection state, it cannot be changed but must turn off the connection and restart.
running tests realtime delay it's still not effective and some devices just don't have a URL tets delay notification indicator.
I hope you will further improve the connection indicator notification section on the notification bar for IOS, APK download platforms, sort by ping, update by time features....

**Comment by KaringX** [comment]
update to 1.0.13.103

**Comment by saeedsh4066** [comment]
ضمن تشکر و عرض سلام ،در نسخه اندروید نمیتوان پینگ سرورها را گرفت، وقتی روی علامت پینگ گرفتن میزنی هیچ عکس‌العملی نشان نمیدهد،امیدوارم در آبدیت بعدی این مشکل حل شود،
با تشکر فراوان.
