### ISSUE TITLE
[FR] 安卓预置分应用代理名单

### ISSUE THREAD

**Issue by ccddos** [KaringX/karing#130]
参考sing-box安卓 实现，可以scan

**Comment by ccddos** [comment]
就是这个页面能不能自动选择app made in CN, 我看singbox安卓有实现

![crop](https://github.com/KaringX/karing/assets/135016091/a982313f-50c4-4cb9-8f10-2c3eae1fa74c)

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27-334  新增 隐藏系统应用 开关
