### ISSUE TITLE
connection close on ios

### ISSUE THREAD

**Issue by MineRX11** [KaringX/karing#136]
hi 

i got problem on ios but didnt find any article or talking about that so here is the video  file 

https://github.com/KaringX/karing/assets/41271485/bcf25b18-d053-44df-83ef-56ffaf362f85

when i click on connect it automatically switch to disconnected immediately pls help me with that

thanks

**Comment by MineRX11** [comment]
ios 17
last version on apple store

**Comment by GooRingX** [comment]
try settings-Delete system VPN configuration

**Comment by GooRingX** [comment]
Try the latest version
