### ISSUE TITLE
软件1.0.14.113闪退

### ISSUE THREAD

**Issue by qianbing233** [KaringX/karing#14]
今天更新后，更新时没有关闭karing旧版本，等到再次倒入节点时就显示服务器失效，请重新选择，重装也没用，这要怎么样解决

**Comment by qianbing233** [comment]
![Screenshot_2024-02-09-23-27-52-494_com miui thirdappassistant](https://github.com/KaringX/karing/assets/59565986/df254e84-ede0-40dd-9452-9550efe2e46c)
这是系统显示的崩溃图

**Comment by KaringX** [comment]
试一下这个版本https://github.com/KaringX/karing/releases/tag/v1.0.13-103

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: qianbing233 ***@***.***>
发送时间: Friday, February 9, 2024 11:47:00 PM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [KaringX/karing] 软件1.0.14.113闪退 (Issue #14)


Screenshot_2024-02-09-23-27-52-494_com.miui.thirdappassistant.jpg (view on web)<https://github.com/KaringX/karing/assets/59565986/df254e84-ede0-40dd-9452-9550efe2e46c>
这是系统显示的崩溃图

―
