### ISSUE TITLE
分应用崩溃

### ISSUE THREAD

**Issue by DDWANY** [KaringX/karing#141]
分应用里勾选白名单应用时，列表越划到最下面，就会出现卡顿以及崩溃😫

**Comment by GooRingX** [comment]
尝试清理内存再试试,应该不是崩溃, 可能是内存占用多被系统杀了.最好能补充一下视频

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27-334 隐藏应用图标
