### ISSUE TITLE
Request: Sharing by link or QR code

### ISSUE THREAD

**Issue by bfapps** [KaringX/karing#142]
Hi. The app is great and thanks for all the efforts you put into it. It was a life saver to me. However, it could be much better if it gave us an option to share link or QR code of our connections. For example, I find a VMESS connection and want to save it for the future before it gets deleted because of updates of my subscriptions. Currently, I’m unable to extract its link and save it to use it later. Please kindly add this feature or let me know if it already exists.

Many thanks in advance,
Best wishes!

**Comment by johnayman0** [comment]
this ⬆️⬆️. 
another feature but i guess it will take sometime is the ability to edit the profile like password, port, sni, etc. like in v2rayN

**Comment by GooRingX** [comment]
> this ⬆️⬆️. another feature but i guess it will take sometime is the ability to edit the profile like password, port, sni, etc. like in v2rayN

1.0.24.282
