### ISSUE TITLE
重启应用后有些订阅失去测速历史

### ISSUE THREAD

**Issue by Zhizhr** [KaringX/karing#145]
在安卓端（1.0.24.282）中有些订阅在每次应用重启后都会失去测速历史，导致应用主界面、我的收藏等中该订阅包含的节点都失去测速历史。失去点击延迟测速单节点的能力。可供测试的订阅链接：（https://server.fylink.link/api/public/sub/2173b39a8fd44f78bd45176569acbf7e/FYLink）

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-283
