### ISSUE TITLE
应用的Android版本频繁崩溃

### ISSUE THREAD

**Issue by Neomanbeta** [KaringX/karing#146]
系统版本：Android 14
系统：OriginOS 4

Karing的设置都是从同一个厂商的OriginOS 3（Android 12）上导入过来的，在那个系统上并无此情况发生。
具体表现为：在冷启动Karing的情况下，弹出界面马上点击连接，几乎99%的情况下Karing会马上崩溃，崩溃后启动再连接，依然马上崩溃，反复。解决办法是启动以后马上切换另外一个任意节点，再点连接，这样崩溃几率就变得非常非常小。

崩溃前后的日志，还有Karing的备份，还有描述情况的录像，都已经在TG上发给过开发者了。
开此issue应开发者要求作为备忘。
我的TG：@RealNeoMan

**Comment by paimi0222** [comment]
我也是这种情况，安卓13的橘子，点连接就崩溃

**Comment by Neomanbeta** [comment]
![QQ截图20240714144052](https://github.com/user-attachments/assets/6cdcf744-a673-4b88-b68c-6ad09931f949)
TG群组有人给出了解决办法，我这里测试有效。之前一直用的模式是mixed，从没有怀疑到这个上面。

**Comment by GooRingX** [comment]
#192
