### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by dani96102** [KaringX/karing#148]
I need prefer ipv6 option in app
Because my domain have both ipv4 and ipv6 and for internets like mtn-irancell in iran we need to use ipv6 for better connection
But some isp's doesnt have ipv6
How can i select and use prefer ipv6 in app?
Please explain or add this option to the karing

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-284
