### ISSUE TITLE
can not start vpn on windows 11

### ISSUE THREAD

**Issue by mgolpayegani** [KaringX/karing#149]
launch process C:\Program Files\Karing\karingService.exe failed: process exit:1:2024/06/17 15:01:26 [31mFATAL[0m[0000]  export.go:51 : decode config at C:\Users\user\AppData\Roaming\karing\karing\karing_service_core.json: outbounds[122].transport.grpc_service_name: json: unknown field "grpc_service_name"

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-285
