### ISSUE TITLE
add tls parameters scan

### ISSUE THREAD

**Issue by ahmadire** [KaringX/karing#151]
The software includes a section called TLS where the _Fragment_ and _Sleep_ parameters need to be adjusted according to the network type. If possible, please add a scanner that can automatically retrieve these parameters and set them within TLS.

**Comment by ahmadire** [comment]
I mean a manner in this way"
https://github.com/Ptechgithub/FragmentScanner

**Comment by GooRingX** [comment]
no plan to support
