### ISSUE TITLE
Black program after installation

### ISSUE THREAD

**Issue by mehdint** [KaringX/karing#156]
Hello
Every version I install the screen goes black 
My Windows 10h22 is the latest update
And this problem after updating the program version 
karing_1.0.23.275_windows_x64 
Happened 
Please check this issue
Thanks

![Capture](https://github.com/KaringX/karing/assets/107259024/251ed0f0-acfe-4b02-ae14-b0cdd476c0a4)

**Comment by GooRingX** [comment]
try https://github.com/KaringX/karing/releases/tag/v1.0.24-291

**Comment by mehdint** [comment]
This problem still exists and has not been resolved. I updated it to the latest version and it turned black again

**Comment by KatanaO** [comment]
I have the same problem. Only this version works normally : karing_1.0.23.275_windows_x64
the other versions have black screen problem. I use portable version.

**Comment by Arianbakhtou** [comment]
same

**Comment by GooRingX** [comment]
Please add the log: Settings-about-Developer Options-view files-karing.log

**Comment by Arianbakhtou** [comment]
> Settings-about-Developer Options-view files-karing.log

screen is black icant find this just this version is ok 1.0.23.275_windows_x64

**Comment by GooRingX** [comment]
C:\Users\xxxxxx\AppData\Roaming\karing\karing, xxxxxx is your system user

**Comment by Arianbakhtou** [comment]
[Uploading karing.log…]()

**Comment by Arianbakhtou** [comment]
[karing.log](https://github.com/user-attachments/files/16069220/karing.log)

**Comment by Arianbakhtou** [comment]
[karing.log](https://github.com/user-attachments/files/16069292/karing.log)

**Comment by mehdint** [comment]
[Uploading karing.log…]()

**Comment by mehdint** [comment]
[karing.log](https://github.com/user-attachments/files/16119379/karing.log)

**Comment by sina1100** [comment]
> This problem still exists and has not been resolved. I updated it to the latest version and it turned black again
> 
> 

سلام موفق شدی ، منم مشکل ش من آن رو دارم و نمی‌دونم چجوری حل میشه و این صفحه سیاه از بین می‌ره 🙏🌹

**Comment by sina1100** [comment]
I have the same problem in Windows 10, it used to be fine, but in higher updates, the screen turns black! I would be grateful if you could help

**Comment by KatanaO** [comment]
base on my searching and talking about this kind of issues on another program that has the same problem (i mean "Hiddify" portable version on windows 11 22h2) i think it's related to problems with the "Flutter" new version and we should wait for it

**Comment by GooRingX** [comment]
基本确认是升级flutter引起,需要flutter官方修复

**Comment by GooRingX** [comment]
Please add GPU information

**Comment by mehdint** [comment]
This problem has been stable for a long time and Karing team is not doing anything for us users

**Comment by GooRingX** [comment]
> This problem has been stable for a long time and Karing team is not doing anything for us users

Waiting for flutter to fix

**Comment by explorecyber** [comment]
This problem baffled me also

**Comment by explorecyber** [comment]
Any version after 1.0.23.275 goes black screen. Thank all the contributors for their commitment, anyhow.

**Comment by GooRingX** [comment]
https://github.com/flutter/flutter/issues/150546

**Comment by GooRingX** [comment]
karing version 1.0.24.283 updated flutter 3.21-> 3.22

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.30.404

**Comment by KatanaO** [comment]
> https://github.com/KaringX/karing/releases/tag/v1.0.30.404

FIXed :)  [v1.0.30.404]
Thanks alot
