### ISSUE TITLE
卡巴斯基 报木马

### ISSUE THREAD

**Issue by 2218675712** [KaringX/karing#158]
事件: 进程已终止
应用程序: karingService.exe
用户: LAPTOP-MEQLBICJ\qisexin
用户类型: 发起者
组件: 系统监控
结果说明: 已终止
类型: 木马
名称: PDM:Trojan.Win32.Bazon.a
威胁级别: 高
对象类型: 进程
对象路径: C:\Program Files\Karing
对象名称: karingService.exe
MD5: BC612F49EF12B5352355E88C3496027F

windows 1.0.24.291

**Comment by GooRingX** [comment]
试一下 1.9.3版本的singbox是否会报?

**Comment by 2218675712** [comment]
还没测试，暂时通过加白名单解决了

**Comment by 2218675712** [comment]
尝试使用 最新版 1.0.24.294 也会报毒
