### ISSUE TITLE
节点信息显示问题

### ISSUE THREAD

**Issue by Neomanbeta** [KaringX/karing#159]
反馈一个显示的问题:节点编辑后，编辑的内容不会马上刷新，长按节点会在弹出菜单里显示节点的IP:PORT，修改保存以后，再长按节点，依然显示修改前的IP:PORT，只有退出karing，重新启动后，再去查看，才会显示编辑后的结果。

**Comment by GooRingX** [comment]
没有复现, 用的哪个版本?

**Comment by Neomanbeta** [comment]
起码最近的3个版本，都是这样，android/ios/win。

**Comment by GooRingX** [comment]
节点编辑后需要退出 '我的配置' 才会将改动更新到配置文件,防止频繁磁盘写操作
