### ISSUE TITLE
Vmess+ws+tls节点无法使用

### ISSUE THREAD

**Issue by trTvT** [KaringX/karing#160]
Nekobox和v2rayng都可以使用，但在karing无法使用，下发的节点配置karing与其他软件都不一样，useragent改成nekobox或者v2ray都依然是一样的问题，文件导入配置也不行。
![IMG_20240623_170905.jpg](https://github.com/KaringX/karing/assets/131618264/09346ba3-7430-4923-8699-f2277ff9beb5)

![IMG_20240623_171131.jpg](https://github.com/KaringX/karing/assets/131618264/795f5b5a-69c1-4c75-84a2-0ac0b19c7485)

或许因为karing的节点配置缺少了tls server name?

**Comment by GooRingX** [comment]
请到 https://t.me/KaringApp 私聊发送测试链接给管理员

**Comment by GooRingX** [comment]
未能提供测试数据,关闭

**Comment by racknerd98** [comment]
> 未能提供测试数据,关闭

碰到了同样的问题，Vmess+ws+tls，自建服务器+cloudlfare CDN
从v2rayN导出链接，然后到karing粘贴，版本是1.2.19.2209
节点能够识别，但是不通。
研究了之后，发现疑似是karing把server和tls的server_name两个混淆了。
如果没有套CDN的情况下，节点的server和tls的server_name是一样的，但是套了cdn后，节点的server是cloudflare的域名或者ip，而tls的server_name是自建服务器的域名。两者不一样。
确认了问题后，手动修改了Vmess+ws+tls节点的tls的server_name，然后节点就通了。

另外还发现一个疑似bug，
在自定义自动选择添加了一个分流组mf，但是在分流规则里怎么都无法显示这个叫mf的组，只能直接选择mf组下的节点。
但是，把这个mf组删除，另外改成其他名字，分流规则里就可以显示并选择这个组了。

**Comment by GooRingX** [comment]
> > 未能提供测试数据,关闭
> 
> 碰到了同样的问题，Vmess+ws+tls，自建服务器+cloudlfare CDN 从v2rayN导出链接，然后到karing粘贴，版本是1.2.19.2209 节点能够识别，但是不通。 研究了之后，发现疑似是karing把server和tls的server_name两个混淆了。 如果没有套CDN的情况下，节点的server和tls的server_name是一样的，但是套了cdn后，节点的server是cloudflare的域名或者ip，而tls的server_name是自建服务器的域名。两者不一样。 确认了问题后，手动修改了Vmess+ws+tls节点的tls的server_name，然后节点就通了。
> 
> 另外还发现一个疑似bug， 在自定义自动选择添加了一个分流组mf，但是在分流规则里怎么都无法显示这个叫mf的组，只能直接选择mf组下的节点。 但是，把这个mf组删除，另外改成其他名字，分流规则里就可以显示并选择这个组了。

tg发原始测试订阅链接(仅需要有问题的节点)给 @ovowe
