### ISSUE TITLE
add priority option for Sub selection or Node selection

### ISSUE THREAD

**Issue by ahmadire** [KaringX/karing#164]
Please add a feature to the software that allows us to prioritize a sub profile or sub address, so that if its servers become available, it automatically connects first regardless of ping time. This would be very helpful when connecting with Warp, as Warp connections initially have high ping times, and the correct ping time is only displayed after a retry.

**Comment by GooRingX** [comment]
新版本延迟测试已考虑了首次连接数据较高的问题
