### ISSUE TITLE
Blackening of the app in most versions

### ISSUE THREAD

**Issue by Matin7697** [KaringX/karing#169]
Hello 
I use any version except 1.0.24.282, the Windows app does not start and turns black, while the VPN works.
I am using the latest version of Windows 11

**Comment by KatanaO** [comment]
i have the same problem on win11, i use portable version and only version no. 1.0.23.275  works fine

**Comment by sina1100** [comment]
Hello
I use any version except 1.0.24.282, the Windows app does not start and turns black, while the VPN works.
I am using the latest version of Windows 10
Thank you for telling me the solution to this problem

**Comment by GooRingX** [comment]
#156
