### ISSUE TITLE
Apps cannot be hidden on Xiaomi devices

### ISSUE THREAD

**Issue by Hongcong60119** [KaringX/karing#170]
Apps cannot be hidden on Xiaomi devices. Swiping close the app automatically disconnects vpn

**Comment by Hongcong60119** [comment]
The app does not support always-on VPN
![Uploading Screenshot_2024-07-08-05-40-29-803_com.android.settings.jpg…]()

**Comment by Hongcong60119** [comment]
![Screenshot_2024-07-08-05-40-29-803_com android settings](https://github.com/KaringX/karing/assets/153686874/5dd3cf5d-370f-413b-a80a-0049329adf7b)

**Comment by Pedro-e** [comment]
And does not support background app Refresh for iPhone
