### ISSUE TITLE
安卓代理失效

### ISSUE THREAD

**Issue by pkwdzc** [KaringX/karing#171]
从1.0.24版本开始，安卓上开启代理服务后，状态栏不会出现vpn图标，连接状态数量也一直是0，任何需要代理的网站都访问不成功，只能降版本到1.0.23使用

**Comment by GooRingX** [comment]
看看是否是把tun模式给禁用了? 设置-TUN

**Comment by pkwdzc** [comment]
> 看看是否是把tun模式给禁用了? 设置-TUN

好吧，高版本确实是需要打开tun模式才能正常使用
