### ISSUE TITLE
去除引起冲突的UA

### ISSUE THREAD

**Issue by ckaak** [KaringX/karing#172]
现在UA：
Karing/1.0.26.323 platform/android ClashMeta;sing-box;clash-verge;NekoBox/Android/1.3.1 (Perfer ClashMeta Format);HiddifyNext;v2ray

使用Xboard面板，https://github.com/cedar2025/Xboard/blob/dev/app/Http/Controllers/V1/Client/ClientController.php 在订阅判断上，会识别clash-verge/NekoBox/HiddifyNext软件版本号，如果低于就不下发节点。

UA改成这样其实也可以让面板下发订阅Karing/1.0.26.323 platform/android ClashMeta;v2ray

**Comment by GooRingX** [comment]
自行手动设置
