### ISSUE TITLE
Disability of connection to Instagram app

### ISSUE THREAD

**Issue by Max-Shaw** [KaringX/karing#174]
Hi. I use Karing on my android phone in Iran. I can easily connect to every censored app or website, but my issue is Instagram app. I can't use Instagram when I use Karing, however I can use it via other VPN apps. Do you know what the problem is??
Thanks for Karing. That's a great app and I have suggested it to many of my friends.

**Comment by GooRingX** [comment]
enable geo rules in geosite, geoip, acl for telegram, and set diversion rules

**Comment by Max-Shaw** [comment]
> enable geo rules in geosite, geoip, acl for telegram, and set diversion rules

Thanks bro. It worked. Fantastic !!
