### ISSUE TITLE
"`HTTPUpgrade `outbound missing '`host`' field. Please add '`host`': ''

### ISSUE THREAD

**Issue by us254** [KaringX/karing#176]
**Key points for issue report:**

• **Missing** "`host`" field in `HTTPUpgrade `config
_**• Current structure:**_
```
  {
    "type": "httpupgrade",
    "path": "",
    "headers": {}
  }
```
**• Requested change:**
  Add "`host`": "" field
• **Rationale:** Host field needed for proper configuration
• **Affects:** sing-box app HTTPUpgrade outbound
• **Request**: Implement "`host`" field in app config

https://sing-box.sagernet.org/configuration/shared/v2ray-transport/#httpupgrade

"`HTTPUpgrade `outbound missing '`host`' field. Please add '`host`': '' to match documentation. Field needed for full configuration support."

**Comment by GooRingX** [comment]
host is already supported. If it is a sing-box configuration, please add the relevant fields yourself. If it is a clash or v2ray subscription connection, please check whether the original configuration has this field. If so, please send the relevant information to the developer or make a note below

**Comment by us254** [comment]
![image](https://github.com/user-attachments/assets/88bba7c1-9311-439d-bf81-d9dd31f8a9db)

Turns out you're totally right about the "host" thing. I think I was rockin' an older version of the app before, and that's what threw me off.
