### ISSUE TITLE
打开某一订阅报错

### ISSUE THREAD

**Issue by wha4up** [KaringX/karing#177]
报错内容
`
start: exception:go.Universe$proxyerror: initialize rule-set[56]: initial rule-set: https://raw.githubusercontent.com/sagernet/sing-geosite/rule-set/geosite-category-ads-all.srs: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-category-ads-all.srs": net/http: TLS handshake timeout | initialize rule-set[56]: initial rule-set: https://raw.githubusercontent.com/sagernet/sing-geosite/rule-set/geosite-cn.srs: Get "https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-cn.srs": context canceled | initialize rule-set[56]: initial rule-set: https://raw.githubusercontent.com/sagernet/sing-geoip/rule-set/geoip-cn.srs: Get "https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs": context canceled
`

同一订阅链接在本应用支持格式的其他应用中能正常使用。

系统平台：安卓11
应用版本：1.0.26.324
订阅类型：Clash

**Comment by GooRingX** [comment]
下载规则集失败,节点问题或者重试,或者直接使用内置规则集

**Comment by GooRingX** [comment]
不同的app拉取到的配置可能是不一样的.karing里删除已添加的有问题的订阅,重新添加,并且将useragent改为仅剩clashMeta
