### ISSUE TITLE
内置规则分流问题

### ISSUE THREAD

**Issue by din1028** [KaringX/karing#180]
软件内置的ACL规则proxygfwlist，命中未被封锁的大陆douyin域名。

![2024-07-17_231016](https://github.com/user-attachments/assets/4b5e6bb4-2cfa-477b-a8cb-160f5cd115f1)
![2024-07-17_231046](https://github.com/user-attachments/assets/675bc0d3-688b-40d5-a5c2-b9e3c14b39a0)

安卓端也是如此

![photo_2024-07-17_23-23-45](https://github.com/user-attachments/assets/3443d39b-7a4e-4fa2-86d8-bcbc0a54bfd1)

所以疑问内置的ACL规则看上去是从ACL4SSR那里扒的，但是原作者的规则没这问题。

而且内置规则是如何更新的呢？不少规则文件的修改时间都是几个月前。

**Comment by GooRingX** [comment]
内核在匹配srs文件有bug,可以先手动添加json格式,使用json格式规则正常

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27-331
