### ISSUE TITLE
Enhancing GeoSite and GeoIP Support for Iran

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [KaringX/karing#183]
**Dear Karing Development Team,**

I hope this message finds you well. I have previously had extensive discussions with the esteemed developer, GooRingX, regarding the improvement of routing, Geosite, and Geoip for Iran in the Karing app. The current implementation is significantly refined compared to its initial state. However, many Iranian websites are still not covered, which can be addressed with some minor adjustments.

**Addition of New Resources for Iranian Users to Karing:**

1. [https://github.com/Chocolate4U/Iran-v2ray-rules/releases](https://github.com/Chocolate4U/Iran-v2ray-rules)

   *Quote:* The above link includes both Geosite and Geoip for Iran and is updated almost weekly. Please add both to Karing with the default auto-update resources.

2. [https://github.com/bootmortis/iran-hosted-domains](https://github.com/bootmortis/iran-hosted-domains)

   *Quote:* The above link covers domains hosted in Iran with weekly updates. Please add both to Karing with the default auto-update resources.

**Addition of the Following Rules to Karing if the User is Iranian:**

1. **Direct Domain Detection for .ir using Regex:**
   ```
   regexp:^.+\.ir$
   regexp:.*\\.ir$
   ```

2. **Enable the Following Rules as Direct:**
   ```
   ext:iran.dat:ir
   ext:iran.dat:other
   geosite:category-ir
   geoip:ir
   geoip:private
   ```

3. **Block Iranian Ads:**
   ```
   ext:iran.dat:ads
   ```

By implementing the above default changes for Iranian users of Karing, it can be said that Karing will have the most comprehensive and straightforward automatic routing rules for Iran.

Additionally, the above points have been written considering the Sing-box and Streisand programs. If needed, the esteemed developer can implement them in Karing with a few modifications in the best possible way.

Thank you very much to the esteemed developers of the outstanding Karing client.

**Best regards, Brooklyn.**

**Comment by oldchiken** [comment]
Very interesting and useful

**Comment by GooRingX** [comment]
规则添加请提交到https://github.com/KaringX/karing-ruleset
