### ISSUE TITLE
VPN disconnection when closing the application

### ISSUE THREAD

**Issue by Hongcong60119** [KaringX/karing#186]
VPN disconnection when closing the application. Please fix it

**Comment by GooRingX** [comment]
Invalid question, please add the platform, karing version, specific phenomenon and resubmit the question

**Comment by Hongcong60119** [comment]
> Câu hỏi không hợp lệ, vui lòng thêm nền tảng, phiên bản karing, hiện tượng cụ thể và gửi lại câu hỏi

Nền tảng android, phiên bản 1.0.27, khi đóng ứng dụng kring vpn tự động ngắt.
