### ISSUE TITLE
Display Issues in the "Preset" Section

### ISSUE THREAD

**Issue by AmirhosseinBrooklyn** [KaringX/karing#187]
**Dear Karing Development Team,**

I hope this message finds you well. Thank you for addressing previous issues. I have encountered a new problem recently and would like to report it.

**Display Issues in the "Preset" Section**

There are three main issues in this section:

1. **Changes to Options Not Displayed:**
   A new problem I have encountered is that when activating options like "Adblock," they do activate, but the tick mark indicating they are active does not remain visible.
**Screen Record:** https://github.com/user-attachments/assets/c7a4ccec-e18e-4c85-b2d7-5cacec02d362

2. **"Apply" Button Overflow on Some Screens:**
   When installing Karing for friends and family, I noticed that the "Apply" button in the "Preset" section, which is also displayed during initial setup and configuration, overflows off the screen, making it difficult to select.
![IMG_4157](https://github.com/user-attachments/assets/9f0a44df-a017-4da2-8ad4-be779ec80248)
   *Quote:* Additionally, please consider a different color for this button to make it easier for users to identify, and reduce the font size of the "Note" section.

3. **Incomplete "Preset" Section:**
   I believe the "Preset" section is a great feature for novice users but lacks the direct setting for "private" by default. Additionally, the current datacenters are incomplete. For instance, several entries for Iran in GeoIP are missing from the Preset.
![IMG_4159](https://github.com/user-attachments/assets/c226eb87-8b06-4a82-9ee3-94a55a1f2faf)

   *Quote:* Adding tips for each Preset could also be useful, especially for options like adblock and adblock plus, explaining their differences. It would also be helpful to clarify if services like Google include all subdomains or just the main domain.

Thank you for your attention to these matters.

**Best regards, Amirhossein Brooklyn**

**Comment by GooRingX** [comment]
1. Click Apply
2. Version 334 will be improved
