### ISSUE TITLE
没法识别我的订阅链接

### ISSUE THREAD

**Issue by freeorgworld** [KaringX/karing#188]
<img width="291" alt="PixPin_2024-07-22_17-20-45" src="https://github.com/user-attachments/assets/0c06e371-b0c4-4a23-a67d-744e87f753bd">

launch process C:\Program Files\Karing\karingService.exe failed: process exit:1:2024/07/22 17:20:14 [31mFATAL[0m[0000]  export.go:51 : start service: post-start outbound/iepl-warp: resolve endpoint domain[sh-iepl2.gorelay.xyz]: name error

我的一个订阅链接，提示这个错误，在 clash 和 stash 上能正常使用

**Comment by GooRingX** [comment]
两个方法:
1. 更换 [代理服务器] dns
2. dns开启 WireGuard 服务器域名预解析
