### ISSUE TITLE
在安卓11上，网络非常慢并且经常出现连接错误

### ISSUE THREAD

**Issue by rwcats** [KaringX/karing#193]
你好，我在Windows和安卓上都使用Karing，但特别是在安卓上网络非常慢，经常断开连接，而在Windows上使用和连接都正常。请问有没有办法解决安卓上的问题？谢谢。
![image](https://github.com/user-attachments/assets/01df6279-834e-4260-b6c2-13cc795066a2)

**Comment by GooRingX** [comment]
更改dns服务器,或者开启fakeip

**Comment by tawayaka** [comment]
> 更改dns服务器,或者开启fakeip

谢谢，但问题仍未解决。
![Screenshot_2024-07-24-11-30-15-329_com nebula karing](https://github.com/user-attachments/assets/bcfa7397-949f-4ca2-a6e5-38b00508be0d)
![Screenshot_2024-07-24-11-30-08-223_org zwanoo android speedtest](https://github.com/user-attachments/assets/617020a7-5d04-46ca-80d8-9f5735c31e89)

**Comment by GooRingX** [comment]
网络检测-输入有问题的域名-检测

**Comment by GooRingX** [comment]
更新到 https://github.com/KaringX/karing/releases/tag/v1.0.28.368 后重置dns试试
