### ISSUE TITLE
App crash on all 1.0.27 beta versions

### ISSUE THREAD

**Issue by loniekovacek** [KaringX/karing#194]
on Android 12 (Samsung s10)
The app works fine on 1.0.26-325
But on all versions from 1.0.27-330 to 1.0.27-334
After closing the app in 'Recent Apps' the app crashes instead of working in background
I have tried to change many options like: 
Disabling tun mode
Disabled ipv6
Changing dns
Clearing the cache
Clearing the data
Reinstalling the app
But no matter what it still crashes

If there is anything I could provide to help please let me know
P.s: I have tried almost all other apps but this one is the best thanks for your hard work

**Comment by GooRingX** [comment]
When you say crash, do you mean the app exits? Or provide relevant screenshots, etc.

**Comment by loniekovacek** [comment]
When the TUN mode is active and the app is open everything is fine :
![Screenshot_20240725_112738_One UI Home](https://github.com/user-attachments/assets/35f8fe7f-dbb2-48d7-8681-2c19681d6219)


after closing the app the 'key icon' on top disappears but the blue icon of the app remains and the system shows this message :
![Screenshot_20240725_111829_One UI Home](https://github.com/user-attachments/assets/b967764c-a217-4c04-83e2-831ec4e4e20c)
Even after disabling the 'TUN mode' by closing the app the crash happens, and the app is disconnected from server but the blue icon of the app is still there

**Comment by javadgh6** [comment]
I also noticed this bug: when the app is closed, the connection is lost on the Android phone.

**Comment by loniekovacek** [comment]
Thanks for your Hard Work
It is fixed in latest beta 1.0.27-335
