### ISSUE TITLE
It MUST runs test without connecting to a server, Not After connecting a server !!!

### ISSUE THREAD

**Issue by Bijan-Pouya** [KaringX/karing#195]
Hello, this is a big problem on your app!
The user needs to know which server is running on their network, obviously!
But most of the time they need to spend a lot of time to find a working server manually, and only then they can start testing all servers, because it needs to connect one server first and then start testing all.
This is very strange, because users need to know which servers are working from their origin network and not from the connected server!!!! So it should run the test without connecting to the server.
the second problem is that the app has a huge memory leak, at least on the ios and macOs,
and the final suggestion is that please consider developing also for tvOs (apple Tv).

**Comment by GooRingX** [comment]
1. Please use auto select
2. Please provide evidence
3. In planning

**Comment by Bijan-Pouya** [comment]
1. most of the time, the auto select keeps connecting to the same servers, sometimes servers have a low latency but don't work, and it causes a problem
2. evidence for what?  it is the way the App is working, it connects and then starts testing, but it has to test without connecting to a server, it is obvious that users need to find the best and working servers on their origin network, maybe servers were blocked or filter on their network but not on the connected server!
