### ISSUE TITLE
安卓端v1.0.27.335版开关按钮不能即时关闭

### ISSUE THREAD

**Issue by wha4up** [KaringX/karing#199]
https://github.com/user-attachments/assets/fddee1d8-1efd-467f-8dfc-ad918648c222

如视频显示，点击开关断开连接后会自动回弹显示开启，不过通知栏没有显示运行图标，实际已断开。

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27.336

**Comment by GooRingX** [comment]
> > https://github.com/KaringX/karing/releases/tag/v1.0.27.336
> 
> 更新了337版和339版，现在开关不会回弹，但会卡个7.8秒才会关闭

出现问题后,设置-关于-开发者选项-查看文件-karing_service.log 内容贴一下
