### ISSUE TITLE
未来是否增加支持安卓

### ISSUE THREAD

**Issue by yueliuLEE** [KaringX/karing#2]
大佬,正如上所说未来是否有意向增加支持安卓,

**Comment by KaringX** [comment]
安卓支持还在开发中

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: yueliuLEE ***@***.***>
发送时间: Tuesday, December 12, 2023 9:42:06 PM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KaringX/karing] 未来是否增加支持安卓 (Issue #2)


大佬,正如上所说未来是否有意向增加支持安卓,

―

**Comment by KaringX** [comment]
close
