### ISSUE TITLE
装在sony电视上使用，如果是hy2协议无法使用

### ISSUE THREAD

**Issue by licxvip** [KaringX/karing#202]
装在sony电视上使用，如果是hy2协议无法使用，进行连接测试，也全部是红叹号，就算开启连接也会马上自动关闭，别的协议没有问题。但是在手机上使用一切正常。

**Comment by GooRingX** [comment]
请补充错误信息(点击叹号)

**Comment by licxvip** [comment]
这三张图片分别是点击叹号重新测试的提示，和打开关闭开关分别弹出的提示
![Uploading IMG_20240729_222035.jpg…]()

**Comment by licxvip** [comment]
![Uploading IMG_20240729_222130.jpg…]()

**Comment by GooRingX** [comment]
电视系统是32位还是64位?安装的是哪个包?

**Comment by licxvip** [comment]
电视应该是32位的安卓9，32位当然安装的是armv7版的安装包了

**Comment by GooRingX** [comment]
更新到339看看第三张图的问题是否还存在

**Comment by licxvip** [comment]
用339版本，不论是测速还是打开开关都不会弹出任何提示了，不过hy2协议测速还都是红叹号，打开开关后很快还是会自动关闭。

**Comment by licxvip** [comment]
电视上还是使用不了，还有修复的希望吗？

**Comment by GooRingX** [comment]
临时方案:可以手动删除hy2节点

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27.346
