### ISSUE TITLE
Automatic selection issue (ios)

### ISSUE THREAD

**Issue by Pedro-e** [KaringX/karing#203]
In most recent versions, there is an issue where there are many servers, but the program does not automatically select them or selects them with a significant delay. I have experienced this issue on iPhone, beta versions, and the latest stable version as well. Thanks to the respected developers.

I have uploaded the log files to help with any potential issues. Thank you for the great Karing program and the esteemed developer.

**Comment by GooRingX** [comment]
Please add video

**Comment by Pedro-e** [comment]
> Please add video

At your request and respectfully, I would like to upload the video of the incorrect operation of the auto-selection section as well as the internet checking.

https://github.com/user-attachments/assets/33faf8ca-b831-4c16-a60d-7d8243c96b2c

**Comment by GooRingX** [comment]
backup and send zip file to the developer by telegram
