### ISSUE TITLE
The proxy whitelist does not work

### ISSUE THREAD

**Issue by Warelax** [KaringX/karing#205]
Hi, it seems to me that the per-app proxy whitelist does not work: when it is enabled, all apps use proxy traffic. Whether they are selected or not. The blacklist is correct. Versions 1.0.27.339_android_arm64.apk and previous ones.

**Comment by GooRingX** [comment]
Please provide the file content of settings-about-developer options-view files-karing_service_core.json

**Comment by Warelax** [comment]
Here is this file: [karing_service_core.json](https://github.com/user-attachments/files/16438809/karing_service_core.json)

**Comment by Warelax** [comment]
Upd: I checked again and saw that this happens when no application is selected.

**Comment by GooRingX** [comment]
From the uploaded configuration, the settings are not written, please submit a screenshot of the perapp settings

**Comment by Warelax** [comment]
Here it is, v.1.0.27.340

![Screenshot_20240802_121438](https://github.com/user-attachments/assets/8e6c9564-9d31-4d1c-b83e-5dd1c48c7b9a)

**Comment by Warelax** [comment]
and this is the current config: 
[karing_service_core.json](https://github.com/user-attachments/files/16468607/karing_service_core.json)

**Comment by GooRingX** [comment]
backup and export , then send me the zip file through telegram

**Comment by GooRingX** [comment]
check the app, then it will work
