### ISSUE TITLE
更多节点类型支持的建议。

### ISSUE THREAD

**Issue by SONGjiemo** [KaringX/karing#21]
感觉目前支持的格式有点问题，
希望可以集成这个开源项目。目前测试ssr，ss这种常用的没有问题。
**[https://github.com/SagerNet/SagerNet]()**
之外反馈过，ssr添加后不支持；希望可以集成他

**Comment by KaringX** [comment]
ssr添加后不支持 :电报群发测试数据给管理员排查

**Comment by KaringX** [comment]
rt
