### ISSUE TITLE
Add feature

### ISSUE THREAD

**Issue by javadgh6** [KaringX/karing#215]
Please add option "import from clipboard" to the add button. As shown in the attached picture.
![Screenshot_20240803_175450](https://github.com/user-attachments/assets/2a08fae5-2619-4f7d-b44e-aa5e5467fffe)

**Comment by GooRingX** [comment]
Since the clipboard data type is uncertain (it may be subscription or local data), it cannot be directly imported into the local node. It is recommended to add it and then merge it
