### ISSUE TITLE
ipv6无法正常使用

### ISSUE THREAD

**Issue by GFDCGFC** [KaringX/karing#218]
我想流量优先走ipv4 ipv6流量全部走直连，ipv6选择开启后还有优先时也没法连接纯ipv6网站，我的节点不支持ipv6要怎么才能让ipv6不走代理能直连

**Comment by GooRingX** [comment]
暂不支持此类分流

**Comment by GFDCGFC** [comment]
下个版本能支持吗
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年8月4日 11:21 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***>,
***@***.***> |
| 主题 | Re: [KaringX/karing] ipv6无法正常使用 (Issue #218) |

暂不支持此类分流

**Comment by GFDCGFC** [comment]
下个版本能支持吗
