### ISSUE TITLE
IOS版的feature request

### ISSUE THREAD

**Issue by egg1234** [KaringX/karing#219]
希望至少在IOS版支持hysteria协议的端口跳跃，另外改进一下hysteria协议设置里面的上行及下行带宽设置的方式，因为现在上下行带宽设置完成后，up及down的栏目里面还是显示23mbps，令人困惑

还有就是能否参考一下FoXray的规则设置方式，至少给用户一个简单的预置规则选项并一键打开，用以绕过国内的域名及国内的ip地址，是否绕过私有网段，以及apple域名是否直连，这4项相信是最常用的，在这方面FoXray预置的simple规则就对用户非常友善

谢谢

**Comment by GooRingX** [comment]
1. 短期无计划支持端口跳跃
2. up/down 的单位就是mbps
3. 到分流里自行设置
