### ISSUE TITLE
在安卓上错误很多

### ISSUE THREAD

**Issue by tyy840913** [KaringX/karing#220]
基本上无法使用，同样的节点用v2rayng连接速度很快，一点问题都没有，那用这个软件就是无法联网，而且使用电信网节点的连接速度很差，很多时候测速失败

**Comment by GooRingX** [comment]
请提供有效错误信息及可供测试的配置

**Comment by wosker** [comment]
发现啦问题原因，必须开tun模式，关掉就无联网
