### ISSUE TITLE
No connection on android!

### ISSUE THREAD

**Issue by javadgh6** [KaringX/karing#223]
The Android app is not able to connect to the network. It shows a green ping but cannot establish a connection. Updating from v1.0.27.342 to v1.0.27.347 also did not resolve the issue. Please check the screen record of my connection.

https://github.com/user-attachments/assets/b4294fae-a4b8-4f9d-af73-6f52bf179f27

**Comment by GooRingX** [comment]
try to reset your dns

**Comment by javadgh6** [comment]
Enabling fake IP and DNS reset seem to solve the issue. Thank you for your help.
