### ISSUE TITLE
适配一下安卓9的国旗图标

### ISSUE THREAD

**Issue by nmanmank** [KaringX/karing#226]
适配一下安卓9的国旗图标，谢谢
Adapt the flag icon to Android 9, thank you
![Screenshot_2024-08-08-19-48-19-89](https://github.com/user-attachments/assets/12d3e048-979b-4ace-962d-8e2079e1a02c)

**Comment by GooRingX** [comment]
该图标由你 的vpn isp提供,请找isp

**Comment by nmanmank** [comment]
什么意思，怎么解决大佬

**Comment by nmanmank** [comment]
> 该图标由你 的VPN isp提供，请找isp

可以具体说一下吗，没有找到你所说的vpnisp

**Comment by nmanmank** [comment]
> 该图标由你 的VPN isp提供，请找isp

可以具体说一下吗，没有找到你所说的vpnisp
