### ISSUE TITLE
【BUG】分流规则严重bug

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#229]
分流规则写chatgpt的域名，发现匹配自动选择规则失效，会匹配final，换成直连规则之后，就匹配成功直连规则，换成当前选择匹配规则也能成功，这是什么问题？
![image](https://github.com/user-attachments/assets/08b8827b-e732-4c11-a94e-0b1bf4d73cba)
![image](https://github.com/user-attachments/assets/5bde51ac-dbbe-4474-bfe9-577725ee8617)
![image](https://github.com/user-attachments/assets/f381226c-357f-40bd-83c9-28f11926e246)
![image](https://github.com/user-attachments/assets/1d0f842d-0aba-4548-a98d-a7a7a9e50ad1)

**Comment by xingxin1590** [comment]
![image](https://github.com/user-attachments/assets/0d9da7f4-68b6-48b9-96d7-9863c000c719)
附带文件也是失效

**Comment by GooRingX** [comment]
经测试,未发现上述问题. 请补充版本号,另外对于远程资源,下载可能有延时,分流检测可能会不对

**Comment by xingxin1590** [comment]
> 经测试,未发现上述问题. 请补充版本号,另外对于远程资源,下载可能有延时,分流检测可能会不对

目前最新版本，然后不只是分流检测，我的连接和日志都是final

**Comment by GooRingX** [comment]
备份-导出发我zip

**Comment by xingxin1590** [comment]
> 备份-导出发我zip

现在规则写完之后无法复现了，等我换台电脑再试一次
