### ISSUE TITLE
【BUG】安卓手机不会出现钥匙图案，代理工具启动，但是手机没有产生代理，依然不能上外网

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#230]
补充一下这是我在通过同步电脑配置之后出现的问题。经过个人检测，是同步功能bug，重置设置和清理缓存之后，代理功能正常启动（单独清理缓存无用），将设置里面的各项配置与电脑端改为一致，发现代理功能任然正常工作（判断为同步功能bug），所以综上不是我配置问题，是同步功能bug（所有同步方式均是如此），有需要我可以提供我的配置文件

**Comment by xingxin1590** [comment]
![Screenshot_20240811_184256_com.nebula.karing.jpg](https://github.com/user-attachments/assets/637368e3-b1fa-45fd-9291-938122abf0f3)

**Comment by GooRingX** [comment]
这不是问题.是你用法问题. pc端默认不开启tun,同步到移动端后,tun被关闭,手动打开即可

**Comment by xingxin1590** [comment]
> 这不是问题.是你用法问题. pc端默认不开启tun,同步到移动端后,tun被关闭,手动打开即可

移动端必须要开tun模式吗？我理解中tun模式一般很少开

**Comment by GooRingX** [comment]
移动端很少不开.除非你的需求就是不开

**Comment by xingxin1590** [comment]
> 移动端很少不开.除非你的需求就是不开

好的，理解
