### ISSUE TITLE
【Feature】希望增加一个功能，代理组可以添加其他代理组

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#231]
我发现自定义代理组是无法添加其他自定义代理组，不如选自动选择，但是有些网页是禁止特定地区访问，所以通过自定义代理组筛选去除特定节点后，不能用一个总的代理组来囊括全部，很不方便

**Comment by GooRingX** [comment]
自定义代理组 就是自定义的自动选择

**Comment by xingxin1590** [comment]
> 自定义代理组 就是自定义的自动选择

理解了，目前是没实现那个功能吧

**Comment by GooRingX** [comment]
短期内无计划支持
