### ISSUE TITLE
【BUG】自定义代理组的候选词正则无效

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#232]
自定义代理组的正则式无效果
![image](https://github.com/user-attachments/assets/4369519d-0474-4b77-afe8-8fb2f852a24e)

**Comment by GooRingX** [comment]
补充详细信息

**Comment by xingxin1590** [comment]
> 补充详细信息

添加以上正则表达式后，自定义代理组依然会选择香港节点

**Comment by GooRingX** [comment]
到选择服务器里使用此正则搜索看结果

**Comment by xingxin1590** [comment]
> 到选择服务器里使用此正则搜索看结果

少写了个判断，生效成功

**Comment by GooRingX** [comment]
导出备份发我

**Comment by xingxin1590** [comment]
> 导出备份发我

[Karing_1.0.27.351_2024-08-12-11-46.backup.zip](https://github.com/user-attachments/files/16577193/Karing_1.0.27.351_2024-08-12-11-46.backup.zip)

**Comment by GooRingX** [comment]
你设置问题. 自定义代理组 候选列表是正则+自己手动勾选的,设置里你打开了隐藏无效节点,所以列表里你看不到 香港高速接入点

**Comment by xingxin1590** [comment]
> 你设置问题. 自定义代理组 候选列表是正则+自己手动勾选的,设置里你打开了隐藏无效节点,所以列表里你看不到 香港高速接入点

我的意思是那个候选词不是排除香港节点吗，为什么还能连上香港节点

**Comment by GooRingX** [comment]
隐藏指的是UI上隐藏,节点数据还是会给到核心
