### ISSUE TITLE
[Bug]修改一些内容，比如自定义代理组会自动重开代理，然后出现断流现象

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#233]
我通过修改自定义代理（不仅限于自定义代理）后自动重开代理后，会出现断流现象（反复断开后重连又断开），通过telegram观测到断流现象，只有手动开关代理才能解决断流问题
![Screenshot_20240812_011320_org.thunderdog.challegram_edit_20765112333810.jpg](https://github.com/user-attachments/assets/fb034bf6-7fcb-417f-b653-5fbf151b1857)

**Comment by Pedro-e** [comment]
我可以确认

**Comment by GooRingX** [comment]
未能复现,请补充详细步骤或者视频

**Comment by shenting1986** [comment]
不好用

**Comment by GooRingX** [comment]
出现断流时候,补充一下:当时使用的是自动选择还是手动选的节点,以及当前节点类型

**Comment by AlphaCatMeow** [comment]
安卓客户端确定有断流现象，每隔1-2秒就断一次，telegram的表现就是总是显示连接中-->成功连接，1-2秒后 连接中-->成功连接，循环下去。使用其他客户端例如v2rayN没有出现过该问题，测试过程中使用的是相同机场同一节点。协议为vmess

**Comment by GooRingX** [comment]
> 安卓客户端确定有断流现象，每隔1-2秒就断一次，telegram的表现就是总是显示连接中-->成功连接，1-2秒后 连接中-->成功连接，循环下去。使用其他客户端例如v2rayN没有出现过该问题，测试过程中使用的是相同机场同一节点。协议为vmess

dns:试试 打开 fakeip, ttl设置为1s

**Comment by GooRingX** [comment]
短时间内(比如几秒)频繁出现断流的,先升级到1.0.34.455, 请备份导出,通过telegram发给开发 gooringx,备注好设备类型,断流现象

**Comment by GooRingX** [comment]
若无信息补充,此issue后续将会被关闭

**Comment by LastNever** [comment]
iphone和windows 也有，得手动重连一下，想换回clash verge了又舍不得webdav
