### ISSUE TITLE
bug 1.0.27.353 desktop

### ISSUE THREAD

**Issue by siiinaaa** [KaringX/karing#239]
1.0.27.353
there is problem with the last desktop version 
every time i connect it i got below massage and after 3-4 times reconnect finally the app turn on i didnt have this issue in pervious version
:
check port failed:SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
, errno = 10048), address = 127.0.0.1, port = 3067

**Comment by GooRingX** [comment]
The port is occupied, there are several solutions:
1. Restart the machine (it may still happen later)
2. Find the process occupying the port and kill the process manually (it may still appear later)
3. karing - Settings - Port Modify 3067 to other unused ports (recommended)

**Comment by siiinaaa** [comment]
thanks but i did all that point but still when i want to change the server and the app trying to reconnecting i have this prob again 
i said that i didnt have this problem in the previous ver...

**Comment by GooRingX** [comment]
When this error occurs, check if there is a karingService.exe process in the task manager?

**Comment by siiinaaa** [comment]
yes it process and that right i think there is problem with  karingService.exe when it disappear i can start the karing again 
and two new point 
1- it just happen in the tune mode / in proxy mode it work fine and 
 2- it just happen when u try to change the server if u just tune it off and on in the one server its ok but if u change the server for 5-10 sec u got this error till  karingService.exe  disappear

**Comment by siiinaaa** [comment]
hello

**Comment by GooRingX** [comment]
Unable to reproduce, if possible please provide steps to reproduce

**Comment by LucidaPlus** [comment]
> Unable to reproduce, if possible please provide steps to reproduce

On Windows, karing 1.0.28.369 still has this issue.
When I turn on/off Auto Route in Tun and back to the main interface, karing's button will reopen, and it may prompt: "Service start timeout", as shown in the following figure:
![image](https://github.com/user-attachments/assets/9cecf70d-0620-48db-a1e4-70d9465816cc)

Then the karing button will turn off, and the open again button will appear:"check port failed:SocketException:....."，The results are shown in the figure below:
![image](https://github.com/user-attachments/assets/245525d3-bfb3-470b-9fe5-951bcd5d80fc)

Of course, this issue occurs when I try to open or close Auto Route multiple times, and it doesn’t happen every time. Additionally, the order of errors like "Service start timeout" and "check port failed: SocketException:....." is not fixed. It might first show the "Service start timeout" error, or it could first display the "check port failed: SocketException:....." error.Here is a GIF of my operation process：
![karing-报错第一次-软件重新打开-01](https://github.com/user-attachments/assets/03d9915e-69aa-470a-8937-fbf3f8984698)

My operating system is Windows 21H2

**Comment by siiinaaa** [comment]
yes that same for me but now in 1.0.28.369  its better then before and it happen just once for me and after that it turn on ! but in the 1.0.27.353 it needed 4-5 time to turn it again

**Comment by LucidaPlus** [comment]
> yes that same for me but now in 1.0.28.369 its better then before and it happen just once for me and after that it turn on ! but in the 1.0.27.353 it needed 4-5 time to turn it again

Yes, the situation has improved, but it has not been completely resolved.
