### ISSUE TITLE
手机后台挂不住，一段时间后app闪退

### ISSUE THREAD

**Issue by gudu11** [KaringX/karing#240]
手机后台挂不住，一段时间后app闪退，后台挂锁，允许后台，无用，安卓10

**Comment by xingxin1590** [comment]
> 手机后台挂不住，一段时间后app闪退，后台挂锁，允许后台，无用，安卓10

我之前也是会杀后台，需要开启手动管理，三个全开

**Comment by GooRingX** [comment]
反馈问题请提供版本及平台信息

**Comment by jixiangruyi999** [comment]
我的也是安卓11过了十几分钟就会闪退，好像最近几个测试版本都是这样

**Comment by GooRingX** [comment]
手动选择节点试试(不使用自动选择)

**Comment by GooRingX** [comment]
#345

**Comment by jixiangruyi999** [comment]
你的现在还有这个问题吗？我的最新版本还是这样。
