### ISSUE TITLE
[BUG]自定义代理组会自动勾选

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#241]
自定义代理组会自动勾选未选择的订阅服务器，如图，确认之后重进，发现自动勾选未选择服务器并且已经实施
![Screenshot_20240814_125146_com.nebula.karing.jpg](https://github.com/user-attachments/assets/ec8ea8a0-d93c-4dfe-8829-a39bacd0dee9)

![Screenshot_20240814_125155_com.nebula.karing.jpg](https://github.com/user-attachments/assets/aea344a9-8077-412c-aaaf-5bda955027e1)

![Screenshot_20240814_125204_com.nebula.karing.jpg](https://github.com/user-attachments/assets/eb4550fc-a984-47f4-93fa-3430231e72b0)

**Comment by GooRingX** [comment]
是不是修改后没有点击右上角的保存?
