### ISSUE TITLE
[BUG]磁贴启动后添加配置文件会把配置文件显示卡没

### ISSUE THREAD

**Issue by xingxin1590** [KaringX/karing#242]
通过磁贴快捷方式启动后，会把配置文件等信息全部变不见（猜测是我在启动期间导入了配置文件），然后开关/重新启动软件（重启手机）均无效果，都无以前的配置文件，但是自动选择显示的服务器是正常的
![Screenshot_20240814_194605_com.nebula.karing.jpg](https://github.com/user-attachments/assets/26ade1d3-d8e2-43f4-8f9f-dfc40de93807)

![Screenshot_20240814_194556_com.nebula.karing.jpg](https://github.com/user-attachments/assets/3f955452-8dac-463b-86f0-3a3fd62b5a20)

![Screenshot_20240814_194601_com.nebula.karing.jpg](https://github.com/user-attachments/assets/c8df5536-6961-4f12-b56d-7f164fdd6430)

![Screenshot_20240814_194917_com.nebula.karing.jpg](https://github.com/user-attachments/assets/06f3141d-67a1-4f7d-97c3-07ee239a097a)

**Comment by GooRingX** [comment]
出现问题后,备份导出zip文件发我
