### ISSUE TITLE
Give me this error 

### ISSUE THREAD

**Issue by wolfkingal2000** [KaringX/karing#248]
1.0.27.353
runtime: program exceeds 200-thread limit
fatal error: thread exhaustion

runtime stack:
runtime.throw({0x756713858a?, 0x400141c1c0?})
	runtime/panic.go:1023 +0x40 fp=0x75e46a19b0 sp=0x75e46a1980 pc=0x7567429300
runtime.checkmcount()
	runtime/proc.go:868 +0xac fp=0x75e46a19e0 sp=0x75e46a19b0 pc=0x756742d3bc
runtime.mReserveID()
	runtime/proc.go:884 +0x3c fp=0x75e46a1a10 sp=0x75e46a19e0 pc=0x756742d40c
runtime.startm(0x400005a008?, 0x0, 0x0)
	runtime/proc.go:2862 +0x110 fp=0x75e46a1a60 sp=0x75e46a1a10 pc=0x7567430f60
runtime.handoffp(0x75ffffffff?)
	runtime/proc.go:2911 +0x47c fp=0x75e46a1a90 sp=0x75e46a1a60 pc=0x75674315ac
runtime.retake(0x81d88f17727f)
	runtime/proc.go:6165 +0x2f8 fp=0x75e46a1af0 sp=0x75e46a1a90 pc=0x756743a0e8
runtime.sysmon()
	runtime/proc.go:6071 +0x3fc fp=0x75e46a1b60 sp=0x75e46a1af0 pc=0x7567439cec
runtime.mstart1()
	runtime/proc.go:1729 +0x88 fp=0x75e46a1b90 sp=0x75e46a1b60 pc=0x756742f048
runtime.mstart0()
	runtime/proc.go:1686 +0x68 fp=0x75e46a1bc0 sp=0x75e46a1b90 pc=0x756

**Comment by GooRingX** [comment]
Version 1.0.28 will be repaired
