### ISSUE TITLE
I don't understand

### ISSUE THREAD

**Issue by qwerzxcva** [KaringX/karing#253]
Can you add a description to each feature, because I'm not particularly good at using it, especially NTP, which I met for the first time, Then you want to add the ability to add plug-ins, such as adguard home, which is especially easy to use as a plug-in. Because he has an upstream dns server, he can choose the best dns for me, It would be nice if karing could also automatically select the lowest latency dns。
Note: I am a small white

**Comment by GooRingX** [comment]
If you have any questions, please consult the telegram group

**Comment by qwerzxcva** [comment]
> 如有疑问，请咨询电报群What's the Telegraph group number, please
