### ISSUE TITLE
[咨询/iOS] 关于Karing使用Adguard规则

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [KaringX/karing#254]
# 描述
Karing 有无使用Adguard规则的解决方案，b站应用的三连弹窗，投票弹窗令人反感， 下面为Adguard适用规则：
bilibili.com##.bili-vote.bili-voted.bili-show
bilibili.com##.bili-guide-all.bili-guide.bili-guide-followed.bili-show
www.bilibili.com##.bpx-player-cmd-dm-inside
www.bilibili.com##DIV[class="bpx-player-cmd-dm-inside"]
# 参考资源
安卓平台xposed模块：https://github.com/zerorooot/FuckBilibiliVote
屏蔽掉B站烦人的视频弹窗(投票、三连弹窗)：https://www.bilibili.com/read/cv10637186/

**Comment by GooRingX** [comment]
等升级1.10内核会支持

**Comment by Sorrow-Scarlet** [comment]
nice,期待，出了踢我一脚

**Comment by GooRingX** [comment]
#251
