### ISSUE TITLE
Wireguard cloudflare warp connection issue

### ISSUE THREAD

**Issue by benyamin95** [KaringX/karing#255]
Since fake_packets_mode (ver 1.0.27.349 and up) got introduced to karing wg warp does not connect in any isp in iran, all 6 modes tested , ipv4 and ipv6 tested , different packets delay and size tested, also ip static and the warp domain tested , Non of the configs work anymore , latest version that still works is 1.0.27.347.
It doesn't matter on android and windows because i can install earlier versions, but ios is impossible . Please fix this issue . Thanks in advance.

**Comment by GooRingX** [comment]
Please provide wg and configuration (fake_packets_mode etc) information for testing

**Comment by misagh72** [comment]
> Please provide wg and configuration (fake_packets_mode etc) information for testing

ulink://install/?content=W3sKInNlcnZlciI6ICIxODguMTE0Ljk3LjE3MCIsCiJzZXJ2ZXJfcG9ydCI6IDMxMzgsCiJ0YWciOiAiSXJhbiBJUCIsCiJ0eXBlIjogIndpcmVndWFyZCIsCiJwcml2YXRlX2tleSI6ICJzQzUyUkZmdjN1MTJVUk5RZmFKNEFvUDR3YWJoMEpJbmFSV2dLajQwRUdJPSIsCiJwZWVyX3B1YmxpY19rZXkiOiAiYm1YT0MrRjFGeEVNRjlkeWlLMkg1LzFTVXR6SDBKdVZvNTFoMndQZmd5bz0iLAoid29ya2VycyI6IDMsCiJtdHUiOiAxMzMwLAoibG9jYWxfYWRkcmVzcyI6IFsKIjE3Mi4xNi4wLjIvMjQiLAoiMjYwNjo0NzAwOjExMDo4ODEwOjhkNjc6YTVlOmEwOGY6NmI4MS8xMjgiCl0sCiJyZXNlcnZlZCI6IFsKMTk3LAo2NiwKMTI0Cl0sCiJmYWtlX3BhY2tldHMiOiAiNDAtODAiLAoiZmFrZV9wYWNrZXRzX3NpemUiOiAiNDAtMTAwIiwKImZha2VfcGFja2V0c19kZWxheSI6ICI0LTgiLAoiZmFrZV9wYWNrZXRzX21vZGUiOiAibTQiCn1d&format=json#Iran%20IP

**Comment by GooRingX** [comment]
> > Please provide wg and configuration (fake_packets_mode etc) information for testing
> 
> ulink://install/?content=W3sKInNlcnZlciI6ICIxODguMTE0Ljk3LjE3MCIsCiJzZXJ2ZXJfcG9ydCI6IDMxMzgsCiJ0YWciOiAiSXJhbiBJUCIsCiJ0eXBlIjogIndpcmVndWFyZCIsCiJwcml2YXRlX2tleSI6ICJzQzUyUkZmdjN1MTJVUk5RZmFKNEFvUDR3YWJoMEpJbmFSV2dLajQwRUdJPSIsCiJwZWVyX3B1YmxpY19rZXkiOiAiYm1YT0MrRjFGeEVNRjlkeWlLMkg1LzFTVXR6SDBKdVZvNTFoMndQZmd5bz0iLAoid29ya2VycyI6IDMsCiJtdHUiOiAxMzMwLAoibG9jYWxfYWRkcmVzcyI6IFsKIjE3Mi4xNi4wLjIvMjQiLAoiMjYwNjo0NzAwOjExMDo4ODEwOjhkNjc6YTVlOmEwOGY6NmI4MS8xMjgiCl0sCiJyZXNlcnZlZCI6IFsKMTk3LAo2NiwKMTI0Cl0sCiJmYWtlX3BhY2tldHMiOiAiNDAtODAiLAoiZmFrZV9wYWNrZXRzX3NpemUiOiAiNDAtMTAwIiwKImZha2VfcGFja2V0c19kZWxheSI6ICI0LTgiLAoiZmFrZV9wYWNrZXRzX21vZGUiOiAibTQiCn1d&format=json#Iran%20IP

test with hiddify 2.0.5, timeout
