### ISSUE TITLE
HTTPUPGRADE configurations not working with HOST field

### ISSUE THREAD

**Issue by IRANWEBFA** [KaringX/karing#256]
httpupgrade configs along with HOST do not work in Karing software, while they work in sing-box and Hiddify software, please check where the problem is.
Thanks

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.360

**Comment by IRANWEBFA** [comment]
> https://github.com/KaringX/karing/releases/tag/v1.0.28.360

I tested this version now, unfortunately the problem is still there.

**Comment by GooRingX** [comment]
send the sub link to developer

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.364
