### ISSUE TITLE
不能手动添加reality信息，enabled选项电脑客户端和手机客户端都打不开选项！

### ISSUE THREAD

**Issue by fanmli** [KaringX/karing#259]
reality选项页面里enabled选项打开不了，没有办法完成信息添加！麻烦作者修复一下谢谢！已经好几个版本不行了。我使用的vless+reality协议！

![Snipaste_2024-08-24_15-21-21](https://github.com/user-attachments/assets/576d029a-afad-4f88-a9da-e26c5d117b71)

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.361
