### ISSUE TITLE
如何更新分流规则

### ISSUE THREAD

**Issue by Doutianbao** [KaringX/karing#26]
153版本可以打开油管，无法上电报
前面版本相反
安卓

**Comment by KaringX** [comment]
1. 使用机场规则
2. 使用内置geosite -设置-分流-geosite-telegram-开启, 回到 分流规则,设置 geosite/telegram对应的分流节点

**Comment by KaringX** [comment]
新建一个分流组,并将分流规则设置为代理服务器,到连接状态里,手动选择相关app,将包名加入到刚才的分流组,保存,返回到主屏即可

Doutian bao ***@***.***> 于2024年3月12日周二 12:29写道：
