### ISSUE TITLE
【BUG】预置[自定义分流组]的开关状态不会被记忆

### ISSUE THREAD

**Issue by cheng1nuo** [KaringX/karing#260]
![image](https://github.com/user-attachments/assets/c3cf5e42-5a94-463b-a8e7-33a46efd9fe7)![image](https://github.com/user-attachments/assets/2d8c2d81-6873-493b-b5fb-4dee7dedab2d)

右图 全选 + 应用以后 再打开这个页面 选项没有记忆开关自动 false 了

为什么不做成同步的呢 或者 修改成只在预置里面显示 不保存到 自定义分流组里面（但是预置开启的分流组照常生效）

**Comment by GooRingX** [comment]
这里是预置的模板,和分流规则并不同步
