### ISSUE TITLE
Please add only proxy functionality-请添加仅代理功能

### ISSUE THREAD

**Issue by qwerzxcva** [KaringX/karing#264]
I am now using other proxies to connect to adguard, and since karing does not have a proxy function, it will collide with adguard VPN. Since there is no root, the system can only let one of them have a VPN, please add a " proxy only " function, thank you-我现在用其他代理连接adguard，由于karing没有仅代理功能，会和adguard撞VPN，由于没有root，系统只能让其中一个拥有VPN，请添加一个“仅代理”功能，谢谢

**Comment by GooRingX** [comment]
Settings-TUN- turn off the TUN Mode
