### ISSUE TITLE
在电视上操作同步配置 webdav 的时候，账号输入框始终无法获取焦点。

### ISSUE THREAD

**Issue by musarona** [KaringX/karing#265]
如题

**Comment by GooRingX** [comment]
可以先使用 局域网同步(https://github.com/KaringX/karing/releases/tag/v1.0.30.410), tv端和移动端版本需要同时>= 410

**Comment by musarona** [comment]
帅！

**Comment by GooRingX** [comment]
[Open with external browser](https://github.com/KaringX/karing/releases/tag/v1.0.37.481)
