### ISSUE TITLE
[功能请求] 自定义分组Ruleset 支持 json5格式

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [KaringX/karing#269]
# 问题
无法导入GKD等使用json5（json拓展格式）格式的广告规则
当前版本无法导入json与srs以外格式的规则（
期待下个版本的adguard规则（txt）

# 参考资料
- https://github.com/gkd-kit/subscription
- https://github.com/Adpro-Team/GKD_THS_List
- https://github.com/KaringX/karing/issues/254

**Comment by Sorrow-Scarlet** [comment]
我又来骚扰你们了2333

**Comment by GooRingX** [comment]
#251
