### ISSUE TITLE
DNS redirection issue

### ISSUE THREAD

**Issue by loniekovacek** [KaringX/karing#272]
1. In v1.0.28.368 and v1.0.28.369
Instead of redirecting raw DNS to designated server it used 'phishing' and 'malware' diversion rules to divert DNS packets
Which in my case is set to 'Block'
[service.log](https://github.com/user-attachments/files/16815026/service.log)

2. After clearing cache and data of app
Now it doesn't work at all
[service.log](https://github.com/user-attachments/files/16815787/service.log)

**Comment by GooRingX** [comment]
more details

**Comment by loniekovacek** [comment]
Thank you it's already fixed in 1.0.28.370
