### ISSUE TITLE
一些国内网站用“全局”模式无法显示的问题

### ISSUE THREAD

**Issue by wowxunlian** [KaringX/karing#275]
比如百度，网易这一类的国内大网，如果连接代理之后用全局模式试图用代理来访问，会直接出现ERR_CONNECTION_CLOSED该页无法显示，我觉得应该是分流规则设置的问题？

我没有设置，用的是软件默认的，请问怎样实现才能得到我想要的效果呢？（即用代理访问国内网站）

**Comment by GooRingX** [comment]
全局就是全部都走代理.至于无法打开,请自行搜索目标站点是否支持你的代理节点
