### ISSUE TITLE
fixes and enhancement

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#281]
Newest version of Hiddify support new types of noises for warp 
Here's codes:
https://github.com/hiddify/hiddify-core/commit/daf33e3065cff29a4ac5450594ba1365eb112ea1

Also "reveresed" parameter for WG:
https://github.com/hiddify/hiddify-core/commit/bc48ec07a8cb85c43a8794b8780c7f732af010d1

Here's examples:
https://github.com/amin4139/share_file/blob/main/Hiddify%2B

https://github.com/Shahabkhan6699/M6/blob/main/M6.json

https://github.com/sahar-km/test/blob/main/testamin.json

https://github.com/Shahab6699/Wow/blob/main/Wow.json

I wish Karing would support these new noise parameters in next updates.

Regards

**Comment by GooRingX** [comment]
It has been supported for a long time. You can find the relevant fields by editing a node.
