### ISSUE TITLE
导入相同公钥/秘钥的Wireguard的 不同配置文件后，实际只有第一个配置文件的endpoint ip 有效

### ISSUE THREAD

**Issue by flyingbug2** [KaringX/karing#284]
感谢开发者迅速修复wg 含ipv6地址时出错的错误。
我在批量导入同一个vpn厂商的不同国家节点（公钥/秘钥相同），发现只有第一个导入的配置文件生效，第二个及以后的配置文件虽然显示工作，但实际使用的是第一个配置文件里的endpoint ip, 纯ipv4和ipv6都这样。不同vpn厂商的配置都有这个错误。

**Comment by flyingbug2** [comment]
> 感谢开发者迅速修复wg 含ipv6地址时出错的错误。 我在批量导入同一个vpn厂商的不同国家节点（公钥/秘钥相同），发现只有第一个导入的配置文件生效，第二个及以后的配置文件虽然显示工作，但实际使用的是第一个配置文件里的endpoint ip, 纯ipv4和ipv6都这样。不同vpn厂商的配置都有这个错误。

补充：不同vpn厂商之间的配置文件（公钥/密钥不同)不会相互干扰，等于每个厂商实际只能导入一个配置。

**Comment by GooRingX** [comment]
请提供测试数据

**Comment by flyingbug2** [comment]
> 请提供测试数据
怎么提供给你测试数据呢？能正常连上需要完整的节点信息，在这里不好公开。能否给个邮件地址，我发给你？或者其它联系方式？

**Comment by GooRingX** [comment]
电报群私聊

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.374
