### ISSUE TITLE
windows 11 报错 以一种访问权限不允许的方式做了一个访问套接字的尝试。

### ISSUE THREAD

**Issue by fxecc** [KaringX/karing#285]
1.0.28.372
check port failed:SocketException: Failed to create server socket (OS Error: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
, errno = 10013), address = 127.0.0.1, port = 3067

**Comment by fxecc** [comment]
搞定了
net stop winnat
netsh interface ipv4 show excludedportrange protocol=tcp
net start winnat
netsh interface ipv4 show excludedportrange protocol=tcp

**Comment by GooRingX** [comment]
此类问题多是端口被其他应用占用,到karing里更改相关端口设置或者关闭占用该端口的应用即可

**Comment by 0day404** [comment]
端口占用的问题，管理员打开终端逐条执行即可
net stop winnat  
netsh interface ipv4 show excludedportrange protocol=tcp  
net start winnat  
netsh interface ipv4 show excludedportrange protocol=tcp
