### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by jixiangruyi999** [KaringX/karing#289]
![68296843-2358-4f1e-ac3d-6095f03454c3](https://github.com/user-attachments/assets/72d35dfd-3bb0-4441-b6ce-8478e6a90602)
安卓11系统最新的几个测试版本打开这几个开关关闭软件重启后又会恢复原样

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.374
