### ISSUE TITLE
软件挂不住后台

### ISSUE THREAD

**Issue by jixiangruyi999** [KaringX/karing#290]
最新的几个测试版本10分钟就掉后台，以前的老版本也会这样，但是以前老版本没现在的严重。希望尽快修复我的是安卓11版本。

**Comment by GooRingX** [comment]
不要重复提交相同问题

**Comment by jixiangruyi999** [comment]
> 不要重复提交相同问题

不好意思，我这边提交了以后没看到问题，然后又提交了一遍
