### ISSUE TITLE
分应用代理，希望加上一键识别国内 App

### ISSUE THREAD

**Issue by heywood2988** [KaringX/karing#291]
singbox Android app 的分应用设置里可以一键扫描并绕开国内 App，这个功能十分方便，![Screenshot_2024-09-06-13-25-06-306_io.nekohasekai.sfa.jpg](https://github.com/user-attachments/assets/ec6a4f7d-d344-4ad7-b702-f73d853b8862)

希望加入此功能！实现代码可参考 singbox，或者 FLclash https://github.com/chen08209/FlClash  ，因为同是 flutter 开发它也是参考 singbox 的代码。
如果实现很困难，就加上导入的功能也可以，参考截图：
![Screenshot_2024-09-06-13-25-38-108_com.github.metacubex.clash.meta.jpg](https://github.com/user-attachments/assets/d23fb077-406d-4b2d-82ba-0553222af68b)

导入的格式是，一行一个包名
com.miui.screenrecorder
com.miui.contentextension
me.mapleaf.calendar

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.375
