### ISSUE TITLE
通知栏流量显示问题

### ISSUE THREAD

**Issue by din1028** [KaringX/karing#294]
第二行最后面那个是流量统计，不应该是速度吧？多出来/s

另外希望流量统计能在前面标识总流量和代理流量，搞成三行显示，第一行显示速度，第二行显示总流量，第三行显示代理流量，这样更容易区分清楚。

![Screenshot_20240908_005153](https://github.com/user-attachments/assets/1b0c22e0-6357-42ea-b53a-2e12d4d2b990)

**Comment by GooRingX** [comment]
流量显示错误375会修复
无法显示3行,系统不支持

**Comment by AndersonGhost** [comment]
我这边显示正常，没有问题
![image](https://github.com/user-attachments/assets/bf654ff7-0343-4cfb-a5dc-18b1f7962c7c)

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.375

**Comment by jxph1123** [comment]
手动能不能有选项关闭这个速度检测，手机端开着这个比较耗电。

**Comment by GooRingX** [comment]
> ###
> **[jxph1123](/jxph1123) ** commented [Oct 12, 2024](#issuecomment-2408374538) •

自己到系统里设置

**Comment by jxph1123** [comment]
> > **[jxph1123](/jxph1123) ** commented [Oct 12, 2024](#issuecomment-2408374538) •
> 
> 自己到系统里设置

在设置里面没有找到可以关掉实时检测速度、代理流量和总流量这个设置。
