### ISSUE TITLE
如何修改某个节点里面的参数配置？

### ISSUE THREAD

**Issue by AndersonGhost** [KaringX/karing#296]
如题所述，请教如何修改某个节点里面的具体配置？例如节点名称，配置参数等

没有发现修改节点配置参数的功能，软件版本：1.0.27.353

对节点的操作只有4个选项：禁用、分享、查看、删除。如下图所示：
![image](https://github.com/user-attachments/assets/7a3b0561-f951-460d-8d53-97a3ba5babab)

**Comment by GooRingX** [comment]
咨询请到电报群咨询群友
