### ISSUE TITLE
Don't Use Front Proxy server as final proxy server (auto select)

### ISSUE THREAD

**Issue by Economic-PunPun** [KaringX/karing#298]
We use front proxy server to get cleaner and better ip address but usually Auto select choose same server as final server. like this:
Data -> Front Proxy Server -> Same Proxy server(Auto select) -> Target
so please Add a checkbox or option to prevent selecting same server by Auto select. (Ignore selected Front Proxy Server in Auto select)

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.28.376

**Comment by Economic-PunPun** [comment]
Thanks
