### ISSUE TITLE
Change Long-Tap to Right-Click in PC version

### ISSUE THREAD

**Issue by Economic-PunPun** [KaringX/karing#299]
despite Mobile Phones (that use Long-Tap), in Desktop Right-Click is used to view context menus and Long-Click is not regular and Widely used. But Karing Uses Long-Click in Desktop version to Disable/Enable a server or Editing. Please Change Long-Tap to right-click in PC version.

**Comment by GooRingX** [comment]
1.0.29.390 will add right click support

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.29.390

**Comment by LittleOwlie** [comment]
Why had 1.2.25.2800 removed this very useful feature on the PC version?
Please return it back - at least as a toggle option in the Developer Settings, because Karing now feels very clunky to configure...
Until then, I will have to stay indefinitely on the previous versions because of it.

**Comment by GooRingX** [comment]
Third-party components are incompatible with the new version of Flutter, so they can no longer be used.
