### ISSUE TITLE
能否增加 ssid 和自定义服务器

### ISSUE THREAD

**Issue by being123321** [KaringX/karing#3]
如题

**Comment by KaringX** [comment]
后续版本会支持

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: being123321 ***@***.***>
发送时间: Saturday, December 23, 2023 12:07:06 AM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KaringX/karing] 能否增加 ssid 和自定义服务器 (Issue #3)


如题

―
