### ISSUE TITLE
请求加入局域网功能 谢谢

### ISSUE THREAD

**Issue by SNAKUAISHITOU** [KaringX/karing#301]
![image](https://github.com/user-attachments/assets/0d213e40-c90b-4ee3-a4b3-9da74c2909d2)
![Uploading photo_2024-09-11_10-55-24.jpg…]()

**Comment by GooRingX** [comment]
设置-共享

**Comment by SNAKUAISHITOU** [comment]
> 设置-共享

设置里没找到啊

**Comment by GooRingX** [comment]
关闭-新手模式

**Comment by haso2007** [comment]
端口在哪里设置
