### ISSUE TITLE
分流规则顺序执行错误

### ISSUE THREAD

**Issue by zhusang** [KaringX/karing#302]
Windows端版本号：1.0.28.378
问题：我创建了一个自定义的分流规则，让gitlab.com走直连，但是在使用域名后缀模式分流的时候会被分流到软件默认的分流组里。
![image](https://github.com/user-attachments/assets/b2e9026d-370f-4592-9df5-687877cbe22d)
![image](https://github.com/user-attachments/assets/f2abcdf1-1879-4398-ba0f-9901ffe9b4f7)
![image](https://github.com/user-attachments/assets/0d7a3e2b-28bc-4784-9d29-fde97e93156c)

当我使用关键字分流时，gitlab的流量会被正确代理。
![image](https://github.com/user-attachments/assets/151b2ab7-4182-4796-b731-ac2913e1826a)
![image](https://github.com/user-attachments/assets/2a6149d5-c315-4a14-93a3-29df4d695023)

**Comment by GooRingX** [comment]
用法错误, 后缀应该是gitlib.com, 具体可以参考singbox1.9.0里关于 domain_suffix 的更新

**Comment by zhusang** [comment]
感谢您的指导。在查看应用程序内的提醒时，注意到域名前添加了一个点。经您解释，现已明晰。非常感谢。
