### ISSUE TITLE
功能 Windows UWP Loopback限制解除

### ISSUE THREAD

**Issue by ElonJunior** [KaringX/karing#306]
### 功能描述
- UWP应用回环访问限制解除工具 (UWP Loopback)
- 参考 https://zhuanlan.zhihu.com/p/29989157

### 优先级
- 低

**Comment by xy3xy3** [comment]
非常需要这个功能

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.32.432
