### ISSUE TITLE
电脑版用备份与同步导出导入到安卓手机版bug

### ISSUE THREAD

**Issue by SNAKUAISHITOU** [KaringX/karing#307]
电脑版用备份与同步导出导入到安卓手机版后不能用，需要重置设置才可以用

**Comment by zhusang** [comment]
同样遇到该问题

**Comment by GooRingX** [comment]
重新设置了什么才能使用?dns?

**Comment by SNAKUAISHITOU** [comment]
> 重新设置了什么才能使用?dns?

 没有设置  重置设置可以用了

**Comment by GooRingX** [comment]
windows版本默认不开启tun, 其他端默认都开启tun.同步后需要手动改一下.由于各个平台差异,不保证导入/同步到其他平台一定能用
