### ISSUE TITLE
最近几个版本都无法打开 在线面板

### ISSUE THREAD

**Issue by jaydong2016** [KaringX/karing#309]
电脑上最近几个版本都无法打开 在线面板，
![Snipaste_2024-09-12_18-52-08](https://github.com/user-attachments/assets/f4c08898-930e-4935-b152-535b9b764b62)

**Comment by GooRingX** [comment]
先到 网络检测里检测 yacd.metacubex.one,看看是什么问题

**Comment by jaydong2016** [comment]
yacd.metacubex.one 域名解析失败。
是这个面板网站没有了

**Comment by jaydong2016** [comment]
替换为这个可用 https://yacd.haishan.me/

这个 https://d.metacubex.one/ 似乎要适配才能使用。

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.29.392 默认已改为https://yacd.haishan.me/, 对于线上的配置,要过1天左右会更新到 https://yacd.haishan.me/
