### ISSUE TITLE
使用剪贴板导入的节点如何编辑

### ISSUE THREAD

**Issue by lleeopen** [KaringX/karing#31]
**使用剪贴板导入的节点如何编辑，或者手动添加节点，像v2rayn那样的双击可以编辑节点内容**

![image](https://github.com/KaringX/karing/assets/35162785/4b01eedd-b8de-4554-9fd8-ad9eee60b85c)

**Comment by KaringX** [comment]
暂不支持

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-282
