### ISSUE TITLE
372版本后对UDP协议DNS支持变差

### ISSUE THREAD

**Issue by john19820** [KaringX/karing#310]
372版本支持全UDP协议DNS正常访问外网，之后的版本都无法支持，希望尽快确认问题，改回来

**Comment by GooRingX** [comment]
分别使用372版本和379版本到
 设置-关于-开发者选项-查看文件-service_core.json 两个版本都将此文件拷贝出来,将文件内容发给开发者.备注好版本号

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.29.395
如果还不行, dns-解析入站域名 禁用
