### ISSUE TITLE
新版本v2ray-worker板创建的节点基本上全红

### ISSUE THREAD

**Issue by tyy840913** [KaringX/karing#311]
同标题，Bpb面板创建的节点没事，但是v2ray-worker创建的节点基本上全红了，回退1.0.28版正常

**Comment by GooRingX** [comment]
请提供测试订阅

**Comment by GooRingX** [comment]
测试结果正常, 看看错误信息,是不是dns有问题(新版改了dns)

**Comment by GooRingX** [comment]
另外自己的订阅信息通过telegram发,不要贴github上
