### ISSUE TITLE
macOS上karing可重现崩溃

### ISSUE THREAD

**Issue by Haifeng-Dai** [KaringX/karing#314]
在macOS上使用karing 1.0.28 (379)，主页点击设置，然后点击返回，karing必定崩溃，系统统计的崩溃信息如下。
[report.txt](https://github.com/user-attachments/files/17001466/report.txt)

**Comment by GooRingX** [comment]
备份-导出 将压缩文件通过telegram发给开发

**Comment by Haifeng-Dai** [comment]
我重新安装了一下karing，在没有任何配置的情况下，主界面点击左上角设置图标，再左上角返回，仍然崩溃。

重新安装后，导出不可用，导出选项点击没有反应。

这应该是软件本身的bug。

**Comment by GooRingX** [comment]
使用1.0.30.414试试,更新了flutter

**Comment by Haifeng-Dai** [comment]
安装尝试了一下，问题已解决
