### ISSUE TITLE
以前能导入的订阅链接现在没法导入了

### ISSUE THREAD

**Issue by cnfree8964** [KaringX/karing#315]
以前能导入的订阅链接现在没法导入了，很奇怪

这是订阅链接：
![00](https://github.com/user-attachments/assets/298fb457-fa95-41fd-8013-93cb78f0fe4c)

https://gist.githubusercontent.com/freeorgworld/5c03561e27f929bdfaf5734bcadd1882/raw/freeorgOP.yaml

1.0.28.379
clash proxies/proxy-providers: No server available

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.29.392
