### ISSUE TITLE
mac端开启局域网连接bug

### ISSUE THREAD

**Issue by DamonLee35** [KaringX/karing#316]
mac端开启局域网共享会导致共享主机本机无法连接代理

**Comment by GooRingX** [comment]
的确有这个问题,可以先使用tun或者本地连接代理指定本机局域网ip而不是127.0.0.1

**Comment by GooRingX** [comment]
1.0.31.423 已修复
开启局域网共享后,如果是手动设置其他软件,设置的代理ip应为本机局域网ip而不是127.0.0.1,如果是使用系统代理,则无需特殊处理
