### ISSUE TITLE
更新订阅链接失败，换成别的软件则正常

### ISSUE THREAD

**Issue by h7g6b2v8cv** [KaringX/karing#317]
1.0.29.391
更新失败:clash proxies/proxy-providers: No server available
Null check operator used on a null value [{type: hysteria2, name: HK-1, server: hk1.atgx.iob, port: 1672, password: FCE6586C-8048-42FD-9C0E-6D8BDC6737D3, udp: true, sni: hk1.atgx.iob}]
Null check operator used on a null value [{type: hysteria2, name: HK-2, server: hk2.atgx.iob, port: 3991, password: FCE6586C-8048-42FD-9C0E-6D8BDC6737D3, udp: true, sni: hk2.atgx.iob}]
Null check operator used on a null value [{type: hysteria2, name: HK-3, server: hk3.atgx.iob, port: 5912, password: FCE6586C-8048-42FD-9C0E-6D8BDC6737D3, udp: true, sni: hk3.atgx.iob}]
Null check operator used on a null value [{type: hysteria2, name: HK-4, server: hk4.atgx.iob, port: 7733, password: FCE6586C-8048-42FD-9C0E-6D8BDC6737D3, udp: true, sni: hk4.atgx.iob}]
Null check operator used on a null value [{type: hysteria2, name: HK-5, server: hk5.atgx.iob, port: 9661, password: FCE6586C-8048-42FD-9C0E-6D8BDC6737D3, udp: true, sni: hk5.atgx.iob}]

同样的订阅链接换clash，singbox，hiddify，V2ray都正常，唯独karing无法导入

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.29.392
