### ISSUE TITLE
关于“静态IP”问题

### ISSUE THREAD

**Issue by h7g6b2v8cv** [KaringX/karing#319]
下边图中红色方框中应该填入什么内容？
我曾经试着填入一个公共ipv4地址，但下次打开后就不见了，很疑惑这个是起什么作用的？
是否和“EDNS Client Subnet”有关？
![IMG_20240915_233948](https://github.com/user-attachments/assets/b1337efe-b263-4f5c-8c99-ff71bc21dce8)

**Comment by GooRingX** [comment]
自定义域名解析

咨询请到telegram群
