### ISSUE TITLE
【功能需求】增加日志过滤和连接过滤

### ISSUE THREAD

**Issue by change41** [KaringX/karing#321]
首先感谢大佬出品的优秀软件，在使用过程中一些小功能需要大佬可以考虑一下
1、在使用Karing时，查找查看指定域名匹配的规则只能通过勾选的方式查看，如果域名请求失败是看不到连接的也就无法看到匹配的规则，希望可以增加自定义输入域名过滤功能而不是通过勾选的方式。
类似Clash：
![image](https://github.com/user-attachments/assets/bd103f13-da75-46a3-aee1-c4535fd5fa3c)

2、在使用日志排查问题时，软件自动的日志查看功能没有过滤功能，且窗口较小不方便查看，然后增加搜索或者过滤功能
类似Clash ：
![image](https://github.com/user-attachments/assets/fa88b87e-fb3f-41bf-9868-949905557371)

**Comment by GooRingX** [comment]
到日志文件搜索
