### ISSUE TITLE
Toggle buttom connect to VPN for MacroDroid

### ISSUE THREAD

**Issue by piscesCat** [KaringX/karing#322]
![IMG_7467](https://github.com/user-attachments/assets/0501229c-894e-4069-99d5-07b9d3c577d9)

I am a user of Karing for Android and I am currently using Termux and MacroDroid on my rooted Android device. I would like to suggest a feature that I believe would be very beneficial.

Feature Request:

I propose adding a shortcut functionality within the app that would allow users to enable or disable the VPN directly from Termux or MacroDroid. This feature would greatly enhance automation and control over VPN settings, especially in scenarios where VPN management needs to be done remotely or on a scheduled basis.

How It Could Work:

	1.	From Termux:
	•	A command or script that can be executed to toggle the VPN state (enable/disable) through Termux.
	2.	From MacroDroid:
	•	Integration that allows creating a macro to control the VPN based on predefined conditions or triggers.

I believe this feature would add significant value to the app and improve its usability​⬤

**Comment by GooRingX** [comment]
karing://connect
karing://disconnect
karing://reconnect

**Comment by piscesCat** [comment]
> karing://connect karing://disconnect karing://reconnect

I fully understand what you’re conveying, but it doesn’t work with any automation apps like MacroDroid. It is essential to create a shortcut launcher similar to the Nekobox app or Sing-box app.

**Comment by GooRingX** [comment]
Please add Nekobox or Sing-box commands or scripts
