### ISSUE TITLE
能打開Youtube網站，但是視頻播放就一直轉圈圈

### ISSUE THREAD

**Issue by stqyz** [KaringX/karing#327]
PC端，Windows系統下，使用karing客戶端開啟代理，不管是否使用tun模式，都是一樣的問題，就是Youtube網站可以正常訪問，但是點擊播放視頻就一直轉圈圈，用Clash客戶端就沒有這個問題，證明不是機場節點的事情。請問得如何設置？

**Comment by GooRingX** [comment]
连接状态里看看对于域名访问使用的节点是否正常,没有没有相关节点访问信息,尝试修改dns

**Comment by GooRingX** [comment]
试试 https://github.com/KaringX/karing/releases/tag/v1.0.29.394

**Comment by stqyz** [comment]
> 试试 https://github.com/KaringX/karing/releases/tag/v1.0.29.394

剛剛試了這個版本的，就可以正常打開Youtube視頻了，看來是我原來安裝的版本的bug，謝謝了哈！
