### ISSUE TITLE
tun 模式如何使用？

### ISSUE THREAD

**Issue by klhlkgeoiun** [KaringX/karing#33]
管理员开启了tun模式后，无法访问网络，win11.
用clash的tun模式是可以的。

**Comment by KaringX** [comment]
使用主屏上的 网络检测 检查网络情况

**Comment by klhlkgeoiun** [comment]
![Snipaste_2024-04-03_09-01-19](https://github.com/KaringX/karing/assets/34825419/f6a9edf1-15e7-431b-a089-96a201121079)
![Snipas
![Snipaste_2024-04-03_09-01-01](https://github.com/KaringX/karing/assets/34825419/4fdcc557-fcb5-4487-8fbb-515bdd1af5ab)
te_2024-04-03_09-01-46](https://github.com/KaringX/karing/assets/34825419/a880f00e-2fa0-436a-aafb-ac8d93b69716)
tun的网卡没连接网络。
用clash的是连接到网络的。
![Snipaste_2024-04-03_09-20-36](https://github.com/KaringX/karing/assets/34825419/cca9794c-d556-48ef-b517-8371c83fd57b)
