### ISSUE TITLE
Profile is not updating, and not sharing (404 Error)

### ISSUE THREAD

**Issue by setarehirani** [KaringX/karing#336]
Hello, profile update is not working. What I figured out is that it removes anything after the domain when profile is added the first time.
so if my subscription link is this: `https://sub.hello.com/link/username`, it adds it the first time, but to update it's fetching the data from `https://sub.hello.com`, and profile sharing would be also to share `https://sub.hello.com`. So it would give 404 error. This is a primary bug which needs to be fixed. Thanks in advance.

**Comment by GooRingX** [comment]
1. Use a browser to open your subscription link to confirm whether the connection is valid
2. If it is valid, please send the subscription link to the developer via Telegram for troubleshooting
