### ISSUE TITLE
[Bug-Report]自定义代理组里选中的订阅更新后，代理组显示无节点可用

### ISSUE THREAD

**Issue by luoqianyi** [KaringX/karing#339]
自定义代理组的节点貌似不会随着订阅节点更新而更新，自定义代理组选中某个订阅，但是订阅更新后之前的节点不见了，这块功能应该是只是做了节点缓存到本地吧？订阅更新后节点变了就找不到了

**Comment by GooRingX** [comment]
订阅节点消失请咨询vpn服务商
可以使用正则规避节点消失导致无法连接的问题
