### ISSUE TITLE
北方聯通下無法連線--BJ

### ISSUE THREAD

**Issue by ctcaib** [KaringX/karing#343]
狀態
使用karing最新版本連線。
DNS使用：
1.默認設定。
2.阿里雲DNS同時勾選谷歌DNS。
3.阿里雲DNS

以上三種都無法進行連線。

切換到中移動的手機網路流量都可以連線。
以上三種狀態，從karing換到其他程式都可以進行連線。

這個狀態反饋給開發團隊，並麻煩再檢查一下DNS編碼，謝謝。

**Comment by GooRingX** [comment]
试试 - 自动设置服务器
