### ISSUE TITLE
能不能再优化一下稳定性？

### ISSUE THREAD

**Issue by jixiangruyi999** [KaringX/karing#345]
我现在是安卓11系统后台还是挂不住，过一段时间就会断开连接闪退，你用其他 Vpn没这个问题，能不能优化一下大佬

**Comment by GooRingX** [comment]
请补充具体'断开连接闪退',比如录个视频

**Comment by jixiangruyi999** [comment]
> 请补充具体'断开连接闪退',比如录个视频

这个我怎么录视频啊？它都是不定时的自动闪退断开链接，我这个手机挂二十几个后台就没有闪退的，但是这个软件有时候30分钟40分钟50分钟，不一定多长时间就会自动断开链接闪退挂不住后台。

**Comment by jixiangruyi999** [comment]
> 请补充具体'断开连接闪退',比如录个视频

前段时间我见别人有一个安卓10的，也反馈过这个问题。

**Comment by jixiangruyi999** [comment]
锁定后台，取消电池优化都不能解决，应该是bug

**Comment by GooRingX** [comment]
闪退断开连接具体现象是什么?比如是主屏上的连接状态变为了 非连接 状态,还是其他的?请描述清楚, 另外发生上述情况时,是使用的 自动选择 还是手动选择的节点?

**Comment by GooRingX** [comment]
新版本和老版本不同,新版本为多进程架构,不会出现因为内核遇到问题导致app也退出的问题(https://github.com/KaringX/karing/issues/240)

**Comment by GooRingX** [comment]
#240

**Comment by jixiangruyi999** [comment]
> 新版本和老版本不同,新版本为多进程架构,不会出现因为内核遇到问题导致app也退出的问题(#240)

这个杀后台以前就有，我用了很多版本的都存在这个问题，是软件软件自动关闭

**Comment by jixiangruyi999** [comment]
不是软件自动断开链接，是软件自动关闭了，那还存在什么链接？

**Comment by jixiangruyi999** [comment]
不能存后台，留不住后台，明白了吗？

**Comment by GooRingX** [comment]
手机什么品牌

**Comment by jixiangruyi999** [comment]
> 手机什么品牌

酷派20pro

**Comment by 824187938** [comment]
我也是总是自己断开不知咋回事

**Comment by jixiangruyi999** [comment]
> 我也是总是自己断开不知咋回事

看来普遍有这个问题，你的是哪个安卓版本？什么手机啊？

**Comment by 824187938** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月27日(周五) 上午8:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [KaringX/karing] 能不能再优化一下稳定性？ (Issue #345)




  
我也是总是自己断开不知咋回事
  
看来普遍有这个问题，你的是哪个安卓版本？什么手机啊？

**Comment by meteorain** [comment]
我也有这个问题，三星s23u，pixel8pro都有这个问题，vpn在后台留不住，电池关闭优化也没用。其他vpn软件比如nekobox和clash meta就没有这个问题。
但ios版的karing没问题。
