### ISSUE TITLE
dns和规则

### ISSUE THREAD

**Issue by YorkJulian49** [KaringX/karing#347]
1.按照singbox官方配置，规则一般顺序是dns_out,clash全局代理,自定义规则,最后是final,但是看在线面板，打圈的看不懂是什么，dns_out应该在最开头出,另外final没有，查询ip77.net,国外地址都是国内ip,可以看出规则的final是没有的.
2.dns服务器设置看不懂，比手搓官方dns设置复杂多了,官方的设置fakeip后就不能dns的final功能，但是karing能够同时选择,还不如自定义
![Screenshot_20240925-162723~2](https://github.com/user-attachments/assets/1e607d85-992c-46c3-9fd2-e0d5b0a56712)
![Screenshot_20240925-162838](https://github.com/user-attachments/assets/5cbaf939-84a3-480e-995d-66521507d86d)

**Comment by heywood2988** [comment]
final 肯定是有的，只是面板里看不到的。详细配置文件可以在开发者选项里找到核心.json 研究～

**Comment by GooRingX** [comment]
在线面板非karing自有功能,不对面板里的功能负责
