### ISSUE TITLE
开启的一瞬间 cpu能占到100%

### ISSUE THREAD

**Issue by Yan-nian** [KaringX/karing#348]
这是咋回事 好像新版本才感觉到的 新给windows装上了 打开的瞬间转圈圈然后 cpu监控显示100%占用 amd7900x
m1的mba 到新版本好像 不如以前丝滑 打开也要转几下
<img width="336" alt="image" src="https://github.com/user-attachments/assets/53ca46ef-46b0-47ed-ab90-78d9bba5cb7b">

**Comment by Yan-nian** [comment]
> 我的绝对完美啊，根本不会出现这种情况cpu点用也非常小0.1%，根本勿略cpu问题
> 
> # 如果TUN添加主界面上，就更方便切换了
> 绝对完美的Karing什么都包含厉害，还内置文本转二维码

哥们 我也没说不好用啊 软件出现特殊情况不是很正常吗 最新的正式版有这种情况 后来我更了pre就没这种情况了

**Comment by mybdye** [comment]
100% 不是上限，开关瞬间都会很卡，Mac Intel，Version 1.0.36 (475)
<img width="892" alt="iShot_2024-12-08_09 33 11" src="https://github.com/user-attachments/assets/0f74d1f5-c35c-40e2-ac94-a6c99b9151b6">

**Comment by GooRingX** [comment]
到 设置里把 连接后自动设置代理 禁用 再试试.设置系统代理的确会占用比较高的cpu

**Comment by mrmyn** [comment]
> 到 设置里把 连接后自动设置代理 禁用 再试试.设置系统代理的确会占用比较高的cpu

不设置系统代理，软件里面需要走外网的应该怎么弄呢？比如终端里面下载软件源之类的

**Comment by auplugroo** [comment]
将设置里面的“始终开启连接”关闭后， 重新打开软件就很丝滑了
