### ISSUE TITLE
TUN mode restart timeout, adjusting rule order, and syncing data

### ISSUE THREAD

**Issue by qiupei** [KaringX/karing#351]
Android phone, client version: 1.0.29.395

Issue: After enabling TUN mode, switching proxy nodes results in a restart failure, with the message "restart: startService timeout". Debug logs have been submitted through the app.

Feature suggestions:

1. When syncing data, can it be implemented to only sync common configurations, while not syncing system-environment-related configurations? For example, the PC version generally uses socks/http proxy, while the mobile version requires TUN mode to be enabled.
2. The Win PC version currently does not allow adjusting the order of traffic routing rules.
3. There are too many configuration items on the configuration page. Can they be categorized?

安卓手机，客户端版本号：1.0.29.395

问题：开启TUN模式后，切换代理节点会重启失败，提示“restart：startService timeout"。调试日志已在app中提交了反馈信息。

功能建议：

1. 同步数据时，是否可以实现仅同步通用的配置，一些与系统环境相关的配置不同步？例如：pc端一般用socks/http代理，而手机端需要开启tun模式
2. Win PC版，目前无法调整分流规则顺序
3. 配置页中，配置项太多，是否能做个分类？

**Comment by GooRingX** [comment]
1. 后续版本考虑加上相关选项
2. 拖拽排序
3. 使用新手模式
