### ISSUE TITLE
总是会莫名其妙重启 VPN 

### ISSUE THREAD

**Issue by heywood2988** [KaringX/karing#352]
以下问题很久了一直存在，
我观察到很多次点进设置看一下，或者点进分流里看一下，并没有修改任何选项，再返回主界面，就归零重启了。电脑版也是如此，有时就拖动一下窗口就又重启，浏览器下载文件，因为速度很快？又重启。阿里云盘下载东西，又观察到重启。
虽然这种重启并不太影响使用，但是挺奇怪的，感觉不太稳定。
![IMG_20240927_211528.png](https://github.com/user-attachments/assets/2f40a744-8152-4ad5-95ca-48b5a6762200)

**Comment by heywood2988** [comment]
按钮会有一个自动开关的动画，时间就归零重启

**Comment by heywood2988** [comment]
难道是因为自动选择变换节点了所以重启 VPN 时间归零？！
这感觉也是挺奇怪

**Comment by GooRingX** [comment]
订阅更新后会自动重新连接,不是bug
