### ISSUE TITLE
如何让CMD能顺利连接Github？

### ISSUE THREAD

**Issue by BoosterCore** [KaringX/karing#355]
请问，当Karing正常运行，浏览器等其它程序都能正常科学上网时，要怎样才能让CMD也正常连接Github等网站呢？
我在网上查了点方法，已经尝试打开了Karing的TUN模式，并在CMD中设置了代理端口（来自于Karing面板显示的端口），但还是无法连接到Github更新代码。

**Comment by GooRingX** [comment]
咨询到telegram群
