### ISSUE TITLE
sub update icon in first screen and ... .

### ISSUE THREAD

**Issue by metalgold23** [KaringX/karing#356]
hi
please add this options:
 1.add subscription update icon in first screen
 2. add turkey language 
 3. add shamsi date
 4. add direct import from clipboard icon
 5. many icons in first screen not important icons(like:speed test,rule,shourtcut,dns options).

**Comment by GooRingX** [comment]
Hope you can help us support turkey translation, project address https://github.com/KaringX/karing-langs
