### ISSUE TITLE
同一个WIFI，电脑正常，手机就不行。这是啥情况。

### ISSUE THREAD

**Issue by Sirius0060** [KaringX/karing#357]
手机是IQOO。
SS用的谷歌云正常，把谷歌云加到karing里也连不上。

**Comment by GooRingX** [comment]
详细描述,补充必要的信息, 如果可能跟订阅有关系,发送订阅链接给开发

**Comment by Sirius0060** [comment]
> 详细描述,补充必要的信息, 如果可能跟订阅有关系,发送订阅链接给开发

跟订阅没关系，用手机流量就正常。
也没改过什么设置。
