### ISSUE TITLE
点击开关，电脑会黑屏重启

### ISSUE THREAD

**Issue by momofrank608** [KaringX/karing#358]
403版本，打开电脑，第一次打开软件，会自动连接，一切正常，但是不能关闭开关。只要打开或关闭开关，电脑就黑屏，重启。测试了好多次了。。。

https://github.com/user-attachments/assets/092db01f-87fb-4636-9a6e-234535a6708e
![photo_2024-09-30_09-03-16](https://github.com/user-attachments/assets/52ad808c-b63b-4967-9689-fe71a03f20b9)

**Comment by GooRingX** [comment]
重新下载安装403
