### ISSUE TITLE
Online panel

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing#359]
Hello,

Thanks so much for the great APP.

I am checking the documenation at https://karing.app/tutorial/.

(https://yacd.haishan.me/?hostname=127.0.0.1&port=3057&secret=xxxx)

Yes, I can make it work in browser by setting secret from service_core.json.

Question upon the online-panel security, I just so curious how does that work for my local VPN connection. Does that mean I am sharing something with haishan.me?

It would be great if you can clarify the question.
Thanks

**Comment by GooRingX** [comment]
1. haishan.me is provided by a third party and does not guarantee their privacy rights
2. For the implementation principle, please refer to https://github.com/haishanh/haishan.me
