### ISSUE TITLE
域名没有解析ip去匹配geoip，导致国内域名匹配到final

### ISSUE THREAD

**Issue by xaoyao** [KaringX/karing#36]
域名没有解析ip去匹配geoip，导致国内域名匹配到final
需要添加domain_strategy配置
参考 https://github.com/MatsuriDayo/nekoray/issues/454
![图片](https://github.com/KaringX/karing/assets/12218604/91689069-e55f-4b76-8dbd-6e901e144c09)

![图片](https://github.com/KaringX/karing/assets/12218604/f8a05fcd-4216-49fd-b716-8d2b2a94bca0)

添加之前
![图片](https://github.com/KaringX/karing/assets/12218604/21a8048f-8949-46cc-9966-98be84f8904b)
添加之后
![图片](https://github.com/KaringX/karing/assets/12218604/a8c8f0b4-a3ef-48aa-927c-4852be2a2477)

**Comment by KaringX** [comment]
1.0.19.195 
domain_strategy 已添加
sniff_override_destination 未添加
