### ISSUE TITLE
导入SSR协议订阅链接报错

### ISSUE THREAD

**Issue by w211691** [KaringX/karing#360]
v2ray: No server available
unsupported shadowsocksr method [rc4]
![image](https://github.com/user-attachments/assets/87c5279e-e8ba-4a0c-80a2-93f7943fc05c)

订阅链接用用ShadowsocksR 4.0可正常订阅。麻烦问下是什么导致无法连接的呢？

**Comment by GooRingX** [comment]
加密算法不支持

**Comment by w211691** [comment]
> 加密算法不支持

好的感谢，找一款同时支持SSR和Clash的客户端好难。。。
