### ISSUE TITLE
连接节点适应一段时间后，无法关闭

### ISSUE THREAD

**Issue by zcm931014** [KaringX/karing#361]
![Screenshot_2024-09-30-17-22-11-23_1bf207af5b79e3fc3ed0ac563baa4869.jpg](https://github.com/user-attachments/assets/5144c160-c1d9-43a8-bdf9-6fb69dc9d943)

安卓版连上节点使用一段时间后，无法关闭节点连接，点击关闭按钮，一直转圈圈，就是无法断开连接，只能强制清理软件进程来关闭软件。但也不是每次都出现这种问题，但问题出现的也比较高频。

**Comment by zcm931014** [comment]
点击关闭按钮一直转不圈圈，无法断开连接。刚连接一会儿可以断开连接 连接时间一长，就无法断开连接。

**Comment by GooRingX** [comment]
控制中心关闭不会有这个问题.此问题暂时无解决方案
