### ISSUE TITLE
amnezia support

### ISSUE THREAD

**Issue by helpmebro911** [KaringX/karing#362]
https://github.com/Slava-Shchipunov/awg-openwrt
https://docs.amnezia.org/en/documentation/amnezia-wg/#working-principle
pls add amnezia support

**Comment by GooRingX** [comment]
No resources support openwrt

**Comment by helpmebro911** [comment]
https://github.com/amnezia-vpn/amnezia-client/releases PC version

**Comment by helpmebro911** [comment]
> No resources support openwrt

https://github.com/amnezia-vpn/amnezia-client/releases PC

**Comment by X-49** [comment]
+1 AmneziaWG would help to use WARP.conf in Karing, for the classic WireGuard protocol is completely detected and blocked in Russia.
