### ISSUE TITLE
Fakeip

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing#363]
Hello,

I checked all of tutorial at https://karing.app/quickstart/

But there is no details upon how to apply fakeip, could you please clarify?

Thanks

**Comment by alexlii1971** [comment]
Thanks, actually i already noted that before post here.

After enabled it, and test on whatismyip, the ip was not changed, it was still the server ip.

So, what should we expect after enabling fake ip?

Is there anything that I misunderstood?

Thanks

**Comment by misagh72** [comment]
yes you misunderstand the purposes of fakeip 
read this 
https://wiki.metacubex.one/config/dns/diagram/?h=fakeip

**Comment by alexlii1971** [comment]
Thanks, so the fakeip mean the IP of DNS, but not the ip of client? right?

If yes, how to check if the fakeIP works?

Thanks

**Comment by GooRingX** [comment]
> Thanks, so the fakeip mean the IP of DNS, but not the ip of client? right?
> 
> If yes, how to check if the fakeIP works?
> 
> Thanks

net check - DNS - Private IP in the analysis result
