### ISSUE TITLE
【功能请求】希望分流规则配置能够同步

### ISSUE THREAD

**Issue by cheng1nuo** [KaringX/karing#364]
Android 端有 应用包名这个分流规则配置 在 Windows 端则是进程名和路径 希望可以Windows 和 Android 能互相显示其平台独占的分流规则配置 以便 webdav 双端配置同步 能同步这些独占配置 以避免 Android 导入了 Windows 的配置导致 原本 Android 的包名分流规则被替换清空

**Comment by GooRingX** [comment]
导入配置是完全替换,不会合并数据
如果想避免,可以将android编辑好后,同步给windows,windows添加完毕后在同步给android(使用新版本),这样就不会丢失
或者导入android前先备份 分应用列表(导出到剪切板),然后在导入windows版本的数据
