### ISSUE TITLE
经常连不上，确定节点没问题，清除缓存后就ok了。

### ISSUE THREAD

**Issue by VerySadPig** [KaringX/karing#368]
安卓手机、win11电脑，经常出现连不上，确定节点没问题（自建的）。
有时候到设置里清理缓存后就ok了。
如果清理缓存无效，就得重启app。
安卓比较不稳定，这种问题较多。

希望能越来越好，我可是卸载了v2和hiddify专注用karing的呀

另，这里可以加一个“手动更新全部结点”的按钮。
![image](https://github.com/user-attachments/assets/bb38fe9a-df43-4448-9413-e125b96e17e6)

**Comment by GooRingX** [comment]
大概率是dns问题,可以重设dns试试
一键更新有,找找看
