### ISSUE TITLE
图标建议反馈：优化图标

### ISSUE THREAD

**Issue by freedomspiritJohn** [KaringX/karing#369]
希望可以优化一下任务栏的图标，现在这个图标长的和小米的热点图标有点像，不太容易区分，希望后续可以换一个美观且容易区分的图标。
![Screenshot_2024-10-02-15-16-15-947_com miui home](https://github.com/user-attachments/assets/680293d6-ef69-4515-8d3b-c0a8079bd89f)

**Comment by GooRingX** [comment]
等UI改版再说
