### ISSUE TITLE
[Bug-Report]windows的webdav一直出现问题

### ISSUE THREAD

**Issue by luoqianyi** [KaringX/karing#371]
![image](https://github.com/user-attachments/assets/307a2c32-7aa5-4efe-ab98-ce1005086e5c)
如上图，点进去就出现这个，但是手机就没有，windows端的端口为什么总是被拒绝呀？

**Comment by GooRingX** [comment]
webdav 服务器地址通过代理访问试试

**Comment by luoqianyi** [comment]
不太行，可能我的电脑网络被玩坏了，什么端口都能被占用

**Comment by GooRingX** [comment]
找个其他的webdav客户端连接试试
