### ISSUE TITLE
[Bug-Report]最新版本开启按钮卡死

### ISSUE THREAD

**Issue by luoqianyi** [KaringX/karing#372]
![image](https://github.com/user-attachments/assets/713219fa-60a8-4bee-be84-f3f0bad7648f)
如图所示

**Comment by luoqianyi** [comment]
窗口的关闭也不生效，只能任务管理器杀死；1

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.30.406
