### ISSUE TITLE
Karing连接之后微信显示无网络连接

### ISSUE THREAD

**Issue by lwl051324** [KaringX/karing#373]
![Screenshot_20241004_123853_WeChat](https://github.com/user-attachments/assets/aa75f0ab-a712-41c7-b82f-cdb1942a7847)
如图所示，微信无网络连接，其他App都正常，折腾了半天无解。全局模式也还是一样无连接(节点正常，油管可以正常打开)。求指点。

**Comment by GooRingX** [comment]
dns或者分流问题.到telegram咨询
