### ISSUE TITLE
自建节点无法连通

### ISSUE THREAD

**Issue by Coldww** [KaringX/karing#374]
自建的节点用V2rayN能连通，这个不行网络检测显示：
No connection could be made because the target machine actively refused it.

**Comment by meteorain** [comment]
我也提一个自建节点的问题。
节点是自建的cloudflare workers或者pages的vless节点，用的是github上的EDtunnel项目代码。
同一个节点同一个网络情况下，Android连不上，ios和win版的karing可以正常连接使用。

**Comment by meteorain** [comment]
> 我也提一个自建节点的问题。 节点是自建的cloudflare workers或者pages的vless节点，用的是github上的EDtunnel项目代码。 同一个节点同一个网络情况下，Android连不上，ios和win版的karing可以正常连接使用。

不小心发现安卓打开fakeip就可以正常使用cf的自建workers节点了！

**Comment by GooRingX** [comment]
> > 我也提一个自建节点的问题。 节点是自建的cloudflare workers或者pages的vless节点，用的是github上的EDtunnel项目代码。 同一个节点同一个网络情况下，Android连不上，ios和win版的karing可以正常连接使用。
> 
> 不小心发现安卓打开fakeip就可以正常使用cf的自建workers节点了！

那就是dns问题,换dns服务器
