### ISSUE TITLE
Add "Server Deduplication" option

### ISSUE THREAD

**Issue by Omegaplexx** [KaringX/karing#375]
In subscriptions with a large number of servers, there are almost always duplicates - servers with identical IP addresses. In many subscriptions they can be difficult to find because of different profile names, different ciphers to the IP address, etc.

I suggest adding an option to the profile settings page that will automatically remove duplicates from the profile.

Thank you for your hard work! Sorry if there's any mistakes in my english

**Comment by GooRingX** [comment]
The same IP address does not mean the same proxy server
