### ISSUE TITLE
😭problems  karing  Samsung  Huawei 😭

### ISSUE THREAD

**Issue by moli1369** [KaringX/karing#376]
Some problems in the program for Samsung and Huawei phones. Crashing and closing the program in all Samsung phones. I tested it myself on the S24. This problem is not working in the background when we close all the programs on the Huawei phone. karing program also closes and does not work in the background, there is no problem in other phones.

**Comment by GooRingX** [comment]
Please provide crash information. The problem cannot be solved based on the above feedback information.

**Comment by GooRingX** [comment]
try  https://github.com/KaringX/karing/releases/tag/v1.0.36.470
