### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by din1028** [KaringX/karing#378]
默认开启的geo大陆直连是第一次使用软件的预置规则，但是在已经有预置的分流组可以导入前提下，预置的geo分流就显得有点规则重复，而且代理方式不能选择直连或当前代理，是定死的，还不如设置可以取消，另外final组能不能改下名称，比如未匹配，漏网之鱼等。

![2024-10-05_1722181](https://github.com/user-attachments/assets/64e3ae69-5aed-4f4c-ab31-111a06a95199)

**Comment by GooRingX** [comment]
没有问题
