### ISSUE TITLE
功能改进及建议

### ISSUE THREAD

**Issue by Jacksmalse** [KaringX/karing#385]
选择服务器界面配置展开后，建议能改成双列的紧凑排布，单列的话节点多了的话得往下划好久，而且界面利用率低。外加能不能选择完节点后切换其它界面后自动收起节点的配置列表，方便下次切换配置。同时建议主界面下方显示出选择的节点的配置组名。

**Comment by GooRingX** [comment]
1. 需要兼容窄屏,尚无计划支持双列
2. 配置列表展开会记住当前展开状态,上方有按钮可以一键收起展开
3. 主界面已有节点配置组名
