### ISSUE TITLE
测试延迟 总是失败

### ISSUE THREAD

**Issue by hyhwl** [KaringX/karing#386]
同一个订阅地址 在karing中全部失败。在hiddify中测试没问题

**Comment by hyhwl** [comment]
也爱报这个
check port failed:SocketException: Failed to create server socket (OS Error: 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。
, errno = 10048), address = 127.0.0.1, port = 3067

请将端口改为其他可用端口或者关闭占用该端口的应用

**Comment by hyhwl** [comment]
cloudflare  pages 搭建的节点

**Comment by GooRingX** [comment]
按提示改端口
