### ISSUE TITLE
规则有误:dl.google.com不应该走直连路线

### ISSUE THREAD

**Issue by Eason0731** [KaringX/karing#387]
重置规则后，发现dl.google.com走的是直连规则，手动添加到国外穿墙也不生效，只能短暂开启全局模式下载谷歌的软件。
影响站点：
Google Drive：https://support.google.com/drive/answer/10838124?hl=zh-Hans#zippy=%2C%E5%AE%89%E8%A3%85%E5%92%8C%E8%AE%BE%E7%BD%AE-windows-%E6%A1%8C%E9%9D%A2%E7%89%88%E4%BA%91%E7%AB%AF%E7%A1%AC%E7%9B%98

Chrome浏览器：https://www.google.com/intl/zh-CN/chrome/

![dl规则](https://github.com/user-attachments/assets/20b46e76-c559-4a15-a7ce-7a2deb7016af)
![Google规则](https://github.com/user-attachments/assets/2f357557-4eb5-4225-99dc-b349186d1026)
![Google下载规则](https://github.com/user-attachments/assets/aa45cf23-da70-4c96-8962-41186305ec8f)

**Comment by GooRingX** [comment]
网络检测检查 dl.google.com 使用的dns服务器是否正常,如果设置了大陆的服务器,可能导致解析后使用直连.分流规则添加预置的google,并将排序靠前
