### ISSUE TITLE
是否可以增加测试下载速度的功能

### ISSUE THREAD

**Issue by veizei-K** [KaringX/karing#388]
v2rayn有测试下载速度的功能，挺方便的，因为有时候延迟低不代表下载速度快，看油管视频或者别的网站视频或者下载的时候有时候速度就很慢。安卓端和电脑端希望都可以支持

**Comment by GooRingX** [comment]
有计划,但是近期不会支持

**Comment by veizei-K** [comment]
> 有计划,但是近期不会支持

![image](https://github.com/user-attachments/assets/fa1166c5-fba2-4955-ba65-4ea63fcd1748)
我理想中的是这样，每一个线路都进行测速，现在karing主页的最上面一排的那个和时速表一样的图标不知道是不是我的问题的解决办法。但还是希望可以同时测速所有的线路，这样我才知道应该选择哪一个
