### ISSUE TITLE
希望在“添加配置链接”处添加关键词过滤选项

### ISSUE THREAD

**Issue by EzSync** [KaringX/karing#389]
如题，希望在“添加配置链接”处添加关键词过滤选项，例如排除或允许含有关键词“美国”或者“UK”的节点。

可以像Gui.for.singbox那样直接添加关键词；

也可以像V2rayN那样支持正则表达式。

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.31.420
