### ISSUE TITLE
二维码添加节点不成功

### ISSUE THREAD

**Issue by Andywang089** [KaringX/karing#390]
二维码已经保存到相册，但是无法读取相册，显示空白![Screenshot_2024-10-12-14-08-49-362_com.nebula.karing.jpg](https://github.com/user-attachments/assets/7a831fdd-2518-405a-90fe-fa2c8b042391)

![Screenshot_2024-10-12-14-08-55-365_com.nebula.karing.jpg](https://github.com/user-attachments/assets/5cec4141-b0a7-453e-8d58-b14f92d68d34)

**Comment by GooRingX** [comment]
1. 如果karing无法打开相册,手动打开kairng读取相册 的权限
2. 如果karing可以打开相册,并且能够选择图片,确认图片没有问题(png, jpg等)的话, 图片通过telegram发给开发

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.31.423
