### ISSUE TITLE
小米 K40 手机，没有读取手机相册的权限

### ISSUE THREAD

**Issue by heywood2988** [KaringX/karing#396]
karing 最新 420 版本 ，此界面点击不了任何选项，读取不到任何图片

![Screenshot_2024-10-15-14-57-00-524_com.nebula.karing.jpg](https://github.com/user-attachments/assets/0ccdb144-5574-4280-8270-c8900aea2d53)

**Comment by heywood2988** [comment]
![Screenshot_2024-10-15-15-03-25-520_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/31ec3365-5445-4c6b-b40f-b3c7055ef5f0)

已开启此相机权限，但是读取不到任何图片

**Comment by GooRingX** [comment]
相册权限,不是相机

**Comment by heywood2988** [comment]
![Screenshot_2024-10-15-15-03-25-520_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/31ec3365-5445-4c6b-b40f-b3c7055ef5f0)

已开启此相机权限，但是读取不到任何图片
没有相册权限
![Screenshot_2024-10-15-16-19-02-694_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/b8a1e613-1c62-4adf-9dbd-133dd049cd26)

**Comment by heywood2988** [comment]
没有相册权限
