### ISSUE TITLE
clash-provider在Karing iOS上不能工作

### ISSUE THREAD

**Issue by zptan** [KaringX/karing#398]
如题，在PC上使用 [clash-verge-rev](https://github.com/clash-verge-rev/clash-verge-rev) 能工作，但是Karing iOS不行：按“连接”按钮显示已连接，但是无法访问被墙的网站。

如果作者需要获取clash-provider配置用于测试，我可以提供

**Comment by GooRingX** [comment]
具体描述

**Comment by GooRingX** [comment]
说清楚如何不工作

**Comment by GooRingX** [comment]
有问题的节点导出发开发

**Comment by GooRingX** [comment]
有问题的节点导出发给开发

**Comment by GooRingX** [comment]
telegram

**Comment by GooRingX** [comment]
> 大陆手机号码无法注册telegram，收不到短信，还有别的方式吗？你们有没有一个对外公开的邮箱？

gooringx@gmail.com

**Comment by GooRingX** [comment]
使用你发的配置可以正常使用代理.到应用数据目录下清空service.log内容后,重新连接,访问google.com后,将日志贴上来

**Comment by GooRingX** [comment]
从日志看,没有发现有出站的请求.同步与备份-导出,将导出的zip邮件发我

**Comment by GooRingX** [comment]
没有看到附件,麻烦重发

**Comment by GooRingX** [comment]
把dns-final里的 alidns移除再试试.我使用windows测试发现final查询结果被污染了,移除alidns恢复正常
