### ISSUE TITLE
安卓版断开连接速度很慢，希望能优化下

### ISSUE THREAD

**Issue by zcm931014** [KaringX/karing#399]
安卓版断开连接速度很慢，经常要转圈好一会儿才能断开连接，而window版本基本没有问题 基本都是秒断开连接 。希望能优化下。
![Screenshot_2024-10-17-23-29-17-18_1bf207af5b79e3fc3ed0ac563baa4869.jpg](https://github.com/user-attachments/assets/c565ef8c-0e85-4c8b-942d-6d6cb4d749bc)

**Comment by GooRingX** [comment]
android 连接一下,如果连接的很慢,到 设置-关于-开发者选项-查看文件-service.log 发上来

**Comment by zcm931014** [comment]
安卓连接很快，断开连接很慢，经常要转圈一会儿才能断开连接。之前没法断开连接，现在优化了，可以断开连接，不过没法像win版本那样秒断开，大神看下能不能优化下。

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.37.487
