### ISSUE TITLE
App可以不收集信息吗？

### ISSUE THREAD

**Issue by zptan** [KaringX/karing#4]
首先感谢作者的工作，给大家提供便利，我刚看到[karing在iOS appstore上架了](https://apps.apple.com/us/app/karing/id6472431552)，恭喜作者

但是看到隐私部分有一点担心，usage和disagonostic我还能理解，但是Contact Info(Email Address)和Identifiers(Device ID)就比较敏感，因为通过这些可以直接定位到用户

希望作者可以不收集这些信息，如果能做到 **_不收集任何信息_** 就最好了

![image](https://github.com/KaringX/karing/assets/17807777/8d2ba1ea-1b8a-41b5-b68a-1ffc5c594506)

**Comment by KaringX** [comment]
email只有使用了app内置的反馈功能并且填写了email才会提交，设备id并不是真实的硬件id，而是app自己生成的uuid

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zptan ***@***.***>
发送时间: Wednesday, December 27, 2023 2:09:35 PM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KaringX/karing] App可以不收集信息吗？ (Issue #4)


首先感谢作者的工作，给大家提供便利，我刚看到karing在iOS appstore上架了<https://apps.apple.com/us/app/karing/id6472431552>，恭喜作者

但是看到隐私部分有一点担心，usage和disagonostic我还能理解，但是Contact Info(Email Address)和Identifiers(Device ID)就比较敏感，因为通过这些可以直接定位到用户

希望作者可以不收集这些信息，如果能做到 不收集任何信息 就最好了

image.png (view on web)<https://github.com/KaringX/karing/assets/17807777/8d2ba1ea-1b8a-41b5-b68a-1ffc5c594506>

―

**Comment by KaringX** [comment]
本app支持多平台

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: zptan ***@***.***>
发送时间: Wednesday, December 27, 2023 4:12:17 PM
收件人: KaringX/karing ***@***.***>
抄送: KaringX ***@***.***>; Comment ***@***.***>
主题: Re: [KaringX/karing] App可以不收集信息吗？ (Issue #4)


好的，谢谢回复

email只有使用了app内置的反馈功能并且填写了email才会提交

也可以不用这个，appstore本身有review功能

我看到有些app会偶尔弹窗问用户“是否对app满意”，然后让用户对app进行评价，然后跳转到appstore里留言打分（最高5星）

―
