### ISSUE TITLE
Google play 应用无法安装

### ISSUE THREAD

**Issue by Andywang089** [KaringX/karing#400]
小米13，系统XIAOMI HperOS
默认模式，Google，Twitter, YouTube, chatgpt, 这些都能打开，谷歌应用市场打不开，后来分流规则把谷歌FCM调成了当前选择后谷歌应用市场可以打开了，但所有软件都无法下载，一直显示等待中
![Screenshot_2024-10-18-14-54-14-390_com android vending](https://github.com/user-attachments/assets/ea1cc196-fb1d-443c-8d38-68dd80372788)

**Comment by Pedro-e** [comment]
Same problem for google play on Samsung

**Comment by GooRingX** [comment]
telegram群咨询群友
