### ISSUE TITLE
使用自签名证书如何添加根证书

### ISSUE THREAD

**Issue by DamonLee35** [KaringX/karing#402]
开发者你好，我使用自签名证书开启tls，为保证安全我想开启证书验证，请问我需要怎样添加根证书到app？

**Comment by DamonLee35** [comment]
karing和singbox添加ca证书验证都会出现如图所示错误：没有权限![Screenshot_2024-10-20-21-56-08-714_io nekohasekai sfa](https://github.com/user-attachments/assets/e4f6d801-d49a-4512-9d2f-160f4b9c6e77)

**Comment by DamonLee35** [comment]
添加证书内容后报错
![Screenshot_2024-10-21-13-01-46-536_com nebula karing](https://github.com/user-attachments/assets/e4a4bab0-e082-4292-80f7-679c3b2f440a)

**Comment by DamonLee35** [comment]
已确认添加证书有bug，使用配置文件导入成功并连接成功，之前通过软件界面导入会导致服务启动失败

**Comment by GooRingX** [comment]
karing不支持添加证书到本机
