### ISSUE TITLE
Can add subscription links normally, but the node cannot be used。

### ISSUE THREAD

**Issue by cqdonghong** [KaringX/karing#406]
This subscription link: https://chromenodes.marcol.top/ It can be added normally, but all nodes cannot be used. Checking the node information is missing relevant content. This subscription link includes Hysteria and VMESS nodes. Adding this subscription link to the NEKORAY software can be used normally, and exporting nodes from NEKORAY to Karing can also be used.

**Comment by GooRingX** [comment]
连接状态看分流,分流有问题调整相关规则,或到telegram群问群友

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.31.426
