### ISSUE TITLE
通过客户端ui界面配置证书bug

### ISSUE THREAD

**Issue by DamonLee35** [KaringX/karing#408]
作者你好，上个issue没说清楚，通过客户端ui界面填入证书内容开启节点会提示服务开启超时，但是可以直接通过配置文件写入证书就可以正常使用，这应该是个bug，如图
![IMG_20241022_154252](https://github.com/user-attachments/assets/348c710c-3e7a-4b1c-8f0f-a56dcecdaa65)
![IMG_20241022_154028](https://github.com/user-attachments/assets/b5f0ec36-48b7-48e1-9336-cfb6e7feb138)

**Comment by GooRingX** [comment]
对比一下使用不同方式添加证书得到的配置的区别,看看是不是手动填入的带入了多余的符号?

**Comment by DamonLee35** [comment]
是的，通过客户端ui添加的证书原本只有1个\的位置会变成2个\\

**Comment by GooRingX** [comment]
app没有问题. 不要拷贝转义过的证书,拷贝原始的证书
