### ISSUE TITLE
日志会疯狂吃磁盘

### ISSUE THREAD

**Issue by atcXiGua** [KaringX/karing#411]
一晚上把我C盘直接干满了，看进程发现service.log文件可以高达几十gb  麻烦大佬看下问题原因，应该是1.0.30.x 的版本。 我现在更新为最新的版本了  1.0.31.429  不知道还会不会有该问题
![image](https://github.com/user-attachments/assets/e4416533-2152-4df3-9718-de2474522ee9)

**Comment by atcXiGua** [comment]
最好是可以加个默认的日志滚动+清理策略

**Comment by GooRingX** [comment]
重现问题的时候,日志内容贴一部分(超过10M就要处理),重新提交问题,本次反馈无有效信息,暂时关闭
