### ISSUE TITLE
Socks5 Subscribe

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [KaringX/karing#415]
Feature description
socks5 has a lot of free node
https://github.com/TuanMinPay/live-proxy

.txt is the most common
https://github.com/TuanMinPay/live-proxy/blob/master/socks5.txt

More Free Node List https://github.com/search?q=proxy+list&type=repositories&s=updated&o=desc

**Comment by GooRingX** [comment]
It does not support non-standard socks formats. You can convert it to socks:// format by your own script and then add it
