### ISSUE TITLE
同一个节点在karing里测速和在v2rayN里测速，相差特别大

### ISSUE THREAD

**Issue by lichaoyangnice** [KaringX/karing#42]
同一个节点，用karing测速，速度只有15Mbps。如果用v2rayN测试，速度可达97Mbps，是哪里的问题呢？
这是karing的：
![image](https://github.com/KaringX/karing/assets/78831777/532c5190-7fd9-48da-9bee-e8579cddfc1a)
这是v2rayN的：
![image](https://github.com/KaringX/karing/assets/78831777/f46d298e-9e17-48bd-ba0f-6105b3902bef)

**Comment by KaringX** [comment]
telegram联系管理员并提供相关配置
