### ISSUE TITLE
自动选择的延迟检测时间间隔设定问题

### ISSUE THREAD

**Issue by huang5307** [KaringX/karing#422]
首先非常感谢作者提供这个工具，非常好用，有个关于延迟检测时间间隔的问题请教。

在 安卓 Karing app 中 “设置/自动选择” 里面的第一个设定是”延迟检测时间间隔“，在我的理解这个设定就是每隔多少时间测试一下代理服务器的延迟及是否能用，在其他的软件例如clash或是sing box，这个时间一般预设是设定为10分钟（10m），但是我看到Karing的预设是8小时（8h），这个让我感到很困惑，这是同一个设定吗？如果用来做延迟检测时间间隔，8小时是不是太夸张了？还是我对这个设定的理解不对？

**Comment by GooRingX** [comment]
依赖于你的节点和网络稳定性,频繁检测会导致电量消耗过快

**Comment by huang5307** [comment]
> 依赖于你的节点和网络稳定性,频繁检测会导致电量消耗过快

我知道可以自己设定，我也有一定的网络理解，我只是想理解我对这个设定的理解是否是正确的吗？--这个设定值是代表每隔多少时间系统去测试配置中所有的节点的延迟。

**Comment by GooRingX** [comment]
自动选择(对应URLTEST)

**Comment by huang5307** [comment]
> 自动选择(对应URLTEST)

ok，thanks
