### ISSUE TITLE
Display proxy speed in Android status bar

### ISSUE THREAD

**Issue by mojtabakaviani** [KaringX/karing#424]
Please display proxy speed in android status bar. it useful to very fast check proxy work or not. for other OS can show in notification area.

**Comment by GooRingX** [comment]
supported

**Comment by mojtabakaviani** [comment]
Proxy speed show in the notification not in status bar!

**Comment by mojtabakaviani** [comment]
Surfboard app have this feature in the notification settings as a Status Bar Speed Icon.

**Comment by GooRingX** [comment]
> @GooRingX Proxy speed show in the notification not in status bar!

sorry, I misread it
