### ISSUE TITLE
custom dns

### ISSUE THREAD

**Issue by nickjp44** [KaringX/karing#426]
hi ,thank you for this great  universal application:

here are some issues i had in current version :
1.the ability to add custom dns are gone now, and i can not add any more,please bring it back.
2.the android tv version , i can not select the connect button any more with my remote control ,and only when connect a usb mouse i can select the button, but in previous version i can easily select the connect button with my remote control,please fix this as well

your app is the best , and thank you for bring vpn to the all devices

**Comment by GooRingX** [comment]
1. https://github.com/KaringX/karing/releases/tag/v1.0.33.440
2. use menu button

**Comment by nickjp44** [comment]
thank you
