### ISSUE TITLE
AndroidTV使用时不能用遥控器。控制的问题

### ISSUE THREAD

**Issue by ericpq** [KaringX/karing#427]
索尼电视，安装后首页不能使用遥控器控制，只能外接鼠标来进行开关操作。其他页面可以使用遥控器控制。
希望能够首页也能使用遥控器控制，或者增加一个开启后自动连接。🤟

**Comment by GooRingX** [comment]
1. 测试未出现这个问题(未使用索尼电视测试)
2. 可以使用 遥控器 菜单 按钮快速切换

**Comment by haso2007** [comment]
退加1.0.30版本就无问题

**Comment by ltdigizone** [comment]
我也有同样的问题

**Comment by haso2007** [comment]
@ltdigizone  另外还有一个问题，就是android的同花顺打开速度很慢，一直显示切换服务器。使用的是默认的分流规则。
但使用v2ray同时的vmess订阅没有此问题。麻烦看一下。

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.34.454
