### ISSUE TITLE
无法测试节点延迟

### ISSUE THREAD

**Issue by helloxz** [KaringX/karing#429]
* 操作系统：Window 10

所有延迟都是感叹号，但是j节点使用正常。

![image](https://github.com/user-attachments/assets/632ed24e-f449-468a-8342-194a7bf75923)

手动点击测试提示：

![image](https://github.com/user-attachments/assets/72325377-077b-426d-a281-b08f33790926)

无论怎么测试结果也一样。

**Comment by GooRingX** [comment]
提供一个有问题的节点配置.上述所给信息无法排查问题
