### ISSUE TITLE
Android版DNS问题

### ISSUE THREAD

**Issue by Risuntsy** [KaringX/karing#431]
版本：1.0.33.441/1.0.33.435

应该没有改任何配置，默认的DNS配置似乎不可用，开了fakeip后似乎正常
![2eb700cdd77445dd325b1b3daad84ec8_720](https://github.com/user-attachments/assets/daf73d40-d7d5-47ba-9644-4a81cb7ceee6)

**Comment by Risuntsy** [comment]
似乎只在新手模式开启的状态下会出现这个问题，关闭新手模式重新开关fakeip似乎没问题

**Comment by GooRingX** [comment]
默认dns保证大部分用户正常使用,无法保证所有用户可以正常使用.出现问题,检测dns延迟手动设置或者使用自动设置dns服务器

**Comment by Risuntsy** [comment]
> 默认dns保证大部分用户正常使用,无法保证所有用户可以正常使用.出现问题,检测dns延迟手动设置或者使用自动设置dns服务器

我试了DNS服务器都是没问题的，但是DNS服务有问题，而且只在开启了新手模式选项状态下不使用fakeip模式会有问题，开、关fakeip状态我这里配置的都是同样的dns服务器
