### ISSUE TITLE
CRITICAL_PROCESS_DIED

### ISSUE THREAD

**Issue by grg456** [KaringX/karing#432]
I have BSOD trying both builds 440 and 441 when I click a button to turn VPN off. 
After the system reboots, I have to manually turn off 'Use proxy server' in Windows Settings app.
Build 435 works fine.

Bug Check String  : CRITICAL_PROCESS_DIED
Bug Check Code    : 0x000000ef
Parameter 1       : ffffdd8f`8258c0c0
Parameter 2       : 00000000`00000000
Parameter 3       : ffffdd8f`896e6080
Parameter 4       : 00000000`00000000
Caused By Driver  : ntoskrnl.exe
Caused By Address : ntoskrnl.exe+414df0
File Description  : NT Kernel & System
Product Name      : Microsoft® Windows® Operating System
Company           : Microsoft Corporation
File Version      : 10.0.22621.4317 (WinBuild.160101.0800)
Processor         : x64
Crash Address     : ntoskrnl.exe+414df0
Processors Count  : 20
Major Version     : 15
Minor Version     : 22621

**Comment by GooRingX** [comment]
is TUN on?

**Comment by grg456** [comment]
No, TUN is off

**Comment by GooRingX** [comment]
try https://github.com/KaringX/karing/releases/tag/v1.0.33.442

**Comment by grg456** [comment]
b442 works fine, no freezes now. Thank you.
