### ISSUE TITLE
小米10手机，安卓13版本，MIUI 14.0.4无法启动

### ISSUE THREAD

**Issue by xfxx2022** [KaringX/karing#44]
安卓版本无法启动，MIUI 14.0.4，安卓13版本，导入连接之后，启动会弹出连接VPN的窗口，确定之后就卡死![photo_2024-04-17_16-51-52](https://github.com/KaringX/karing/assets/25678988/3dcff27d-db0c-4d82-9b36-b71d12366f68)

**Comment by xfxx2022** [comment]
删除系统vpn配置之后重试也不行，设置-关于-双击图标-开发者选项-查看文件，karing-service.log文件，请查收[karing_service.log](https://github.com/KaringX/karing/files/15009062/karing_service.log)

**Comment by KaringX** [comment]
1.0.19.206
