### ISSUE TITLE
451版本，明明选中的是这个节点，实际却是另外的节点

### ISSUE THREAD

**Issue by starifly** [KaringX/karing#442]
最近这些版本包括最新版，手动选中的是某个节点，有时候查ip却有另外的节点ip出现（非必现），请作者帮忙查明一下是什么原因。有需要我提供更多信息的，请随时提出，谢谢。

**Comment by GooRingX** [comment]
检查自己的分流设置

**Comment by starifly** [comment]
谢谢解答，应该是这个原因，不知道什么时候final切换到自动选择了。
