### ISSUE TITLE
Novice Problem

### ISSUE THREAD

**Issue by bjerfan** [KaringX/karing#443]
Hello dear, by default novice will be turned to "ON" on iOS (Same effect on android and windows if using TUN) and it makes my phone not be able to work in browser, i tried so many things and noticed that if my Novice mode is ON my browsers dont work, for example in-app like instagram or youtube works fine but if i go to my safari or google chrome and type in instagram.com or youtube.com nothing loads in, Can we have novice turned off by default?

**Comment by GooRingX** [comment]
Novice is for users who are not familiar with Karing. If you are already familiar with Karing, please turn off Novice mode. As for the problem you mentioned, the DNS does not go through the proxy in Novice mode, so the default DNS may be different. You can manually check and set it.
