### ISSUE TITLE
[Enhancement] : bypassing Captive Portal in "tun-in" (only android)

### ISSUE THREAD

**Issue by Graveyard9988** [KaringX/karing#445]
Hello

As you may know that there's an ability in Android phones that you can login at public wifi or skip ads.

This ability called "Captive Portal" which is a system app is included in all Android devices.

In Sing-Box docs, you can only bypass it in "tun-in" part of sing box config that I'm gonna show you an example (official doc):

https://github.com/SagerNet/sing-box/blob/77fec189a117bd7e9adde098483bdb14d1dfb0f4/docs/configuration/inbound/tun.md?plain=1#L131

  "exclude_package": [
    "com.android.captiveportallogin"
  ],

You can add above (exclude package for Captive Portal) for Android version of Karing.

This is highly essential for Iran, China, Russia, Myanmar & other countries  that people have to connect wifi when they need. by adding this ability, they won't need to disconnect Karing to login public wifi. So, they data will be kept safe.

I hope you consider this problem.

Thanks for your always great job. 

Regards

**Comment by GooRingX** [comment]
Settings-TUN-Per-App Proxy - disable Whiltelist Mode
