### ISSUE TITLE
Apple Tv App

### ISSUE THREAD

**Issue by hayderi** [KaringX/karing#446]
The apple tv app disconnects after sometime specially when doing speedtest.

**Comment by GooRingX** [comment]
Upgrade both ios and tvos to 1.0.34.453, use speedtest to test tvos, after tvos karing is disconnected, use ios to scan and connect to tvos karing, use ios karing to view service_core.log, service_error.log, and add the file contents to the following

**Comment by GooRingX** [comment]
Failed to provide valid information, closed
