### ISSUE TITLE
High memory usage bug in macos version!!!

### ISSUE THREAD

**Issue by javadgh6** [KaringX/karing#448]
There is a bug in the latest version of the software that causes high memory and CPU usage, making the system slow and unresponsive.
<img width="608" alt="Screenshot 2024-11-11 at 18 14 39" src="https://github.com/user-attachments/assets/9398efe4-598d-4050-be20-fca1857d22e0">

**Comment by GooRingX** [comment]
which version?

**Comment by GooRingX** [comment]
try version:1.0.33.445

**Comment by javadgh6** [comment]
version 1.0.33.446

**Comment by GooRingX** [comment]
testflight

**Comment by GooRingX** [comment]
(testflight) try https://github.com/KaringX/karing/releases/tag/v1.0.34.457

**Comment by javadgh6** [comment]
> (testflight) try https://github.com/KaringX/karing/releases/tag/v1.0.34.457

This new version is a significant upgrade, also addressing the issue from #197.
