### ISSUE TITLE
添加订阅出错

### ISSUE THREAD

**Issue by midpoint** [KaringX/karing#454]
1.0.34.456
添加失败:download profile failed: exception:HandshakeException: Handshake error in client (OS Error: 
	WRONG_VERSION_NUMBER(../../../flutter/third_party/boringssl/src/ssl/tls_record.cc:231))
, 请打开代理或者修改当前代理节点后重试

**Comment by GooRingX** [comment]
tls不兼容。手动下载配置后导入
