### ISSUE TITLE
IP规则集的no resolve实现

### ISSUE THREAD

**Issue by keeejiii** [KaringX/karing#458]
觉得内置的geoip不够用，想使用自己导入geoip ruleset，但是这个ip规则集不能实现clash的no resolve效果，会对ip进行dns解析，只有内置的geoip才能实现no resolve。能否对用户自行导入的IP规则集实现clash的no resolve效果？或者允许用户更换内置的geo的url

**Comment by GooRingX** [comment]
ip不会解析。domain可以在dns-解析入站域名 控制是否解析为ip后分流。不支持替换内置（功能有 依赖）

**Comment by keeejiii** [comment]
就是我想导入一个IP ruleset，作为一个直连策略组，这种IP规则集会对IP进行解析吗？
