### ISSUE TITLE
win 版如何设置域名白名单呀?

### ISSUE THREAD

**Issue by xh2cgp001** [KaringX/karing#46]
现在 本地host 进行了域名重定向,如何在使用karing 的时候  域名重定向的这些域名不走代理,而是直连
这个要怎么设置呢

**Comment by GooRingX** [comment]
分流-自定义分流组 添加到域名
到分流规则指定上面添加的分组的分流规则为直连

**Comment by xh2cgp001** [comment]
感谢 已经解决了, 同时需要注意的是 如果启用了 DNS分流规则,则需要把直连流量设置为 local
