### ISSUE TITLE
karing 使用 tun 模式后，局域网内其他电脑无法 ssh 访问该主机 

### ISSUE THREAD

**Issue by LastNever** [KaringX/karing#461]
之前用 clash verge 设置某些 ip 排除在 tun 模式以外后可以正常连接

现在想多端同步，于是换了 karing，发现同样的问题，关闭 tun 模式正常连接，请问 karing 有相关配置排除走tun吗

至于为什么非要用 tun 模式，因为 wsl 设置 http 代理不生效，所以开的 tun

**Comment by GooRingX** [comment]
[参考官方教程](https://karing.app/blog/case/wsl2)
