### ISSUE TITLE
机场地址输入了保存不了

### ISSUE THREAD

**Issue by Joshuagpt** [KaringX/karing#463]
简直折磨人的耐心

**Comment by Joshuagpt** [comment]
电视机版本的

**Comment by GooRingX** [comment]
将 设置-关于-开发者选项-查看文件-app.log 上传
另外反馈问题,把 karing版本号带上

**Comment by GooRingX** [comment]
如果app.log为空,请telegram 联系 gooringx vowe

**Comment by GooRingX** [comment]
试试 https://github.com/KaringX/karing/releases/tag/v1.0.36.470
