### ISSUE TITLE
issue error tun

### ISSUE THREAD

**Issue by mozzaru** [KaringX/karing#464]
i use cf account 
And I saw in the log mode info 
And an error occurred 
"[error]	[3768365458 10.42s] default.go:195 inbound/tun[tun_in]: io: read/write on closed pipe | upstream: context canceled, packet connection from [10.20.0.1:42304] to: [10.20.0.2:53"
![Screenshot_2024-11-20-12-44-30-67_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/6a807847-baa3-4c9a-b337-f8ee990bdc0d)

There is a solution to this?
Thanks before

**Comment by GooRingX** [comment]
Normal no need to worry
