### ISSUE TITLE
请问到底那个在控制分流？

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing#467]
有两个设置分流的地方：

分流
<img width="395" alt="Screen Shot 2024-11-20 at 21 17 14" src="https://github.com/user-attachments/assets/39a29f6b-e24c-474e-884d-113192be3b98">

DNS
<img width="393" alt="Screen Shot 2024-11-20 at 21 17 46" src="https://github.com/user-attachments/assets/82781ac2-45da-4e4d-bf25-1fb4260a9c4f">

这二者有何区别？谢谢

**Comment by GooRingX** [comment]
> 有两个设置分流的地方：
> 
> 分流 <img alt="Screen Shot 2024-11-20 at 21 17 14" width="395" src="https://private-user-images.githubusercontent.com/15896194/388107112-39a29f6b-e24c-474e-884d-113192be3b98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTIyMzgsIm5iZiI6MTczMjE1MTkzOCwicGF0aCI6Ii8xNTg5NjE5NC8zODgxMDcxMTItMzlhMjlmNmItZTI0Yy00NzRlLTg4NGQtMTEzMTkyYmUzYjk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxMTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyNmM5NzA3MDJhNzk0YWQ0YWZiYjcxZjI3NmQyOTYyMzZkYzk5NjFkNDUyYTdlMjI2NDJjNDgxMzEzMDA1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Co4rJ8Fbw07wZdvD3uZwgsQdaSnZgL5104-TX5D7hPY">
> 
> DNS <img alt="Screen Shot 2024-11-20 at 21 17 46" width="393" src="https://private-user-images.githubusercontent.com/15896194/388107324-82781ac2-45da-4e4d-bf25-1fb4260a9c4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTIyMzgsIm5iZiI6MTczMjE1MTkzOCwicGF0aCI6Ii8xNTg5NjE5NC8zODgxMDczMjQtODI3ODFhYzItNDVkYS00ZTRkLWJmMjUtMWZiNDI2MGE5YzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxMTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNzI0OGY3NDA5MTgzZDU1MGQ2OGFiNDc4YmYyMTBlMDdmM2ViYjY3ZGIwNmVjOGE4NmQ5YmRhMjFmODc0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vtb3pmMnwqRPN2zYkEAVZpJ33lB_yNExvAlK13CT8aA">
> 
> 这二者有何区别？谢谢

dns分流指的是根据分流规则,dns选择对应的dns服务器解析

**Comment by GooRingX** [comment]
> 一旦设置到全局，网络往往不同，无法打开任何网页。 而系统代理虽然会添加三个代理到Mac网络连接下的proxies里。 <img alt="Screen Shot 2024-11-21 at 01 00 52" width="643" src="https://private-user-images.githubusercontent.com/15896194/388193409-5d486ae6-781e-44a3-b250-e5d5a5273ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTIyMzgsIm5iZiI6MTczMjE1MTkzOCwicGF0aCI6Ii8xNTg5NjE5NC8zODgxOTM0MDktNWQ0ODZhZTYtNzgxZS00NGEzLWIyNTAtZTVkNWE1MjczYWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxMTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ODNjODVhNGU4OWUzN2QyYTEzOTFjNWJhNjFlOTU4ODQyZTY0OWY2MjlhNzQ3ZjkwNDRhMGI3M2I1OWJjNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wsX1fvrHQ-OPmB4fX1VPVSO05QiQjMFwk-02D0p9uuU">
> 
> 比较迷茫的是，经常设置到全局、系统代理时，网络根本不通，无法打开任何网页。
> 
> 请问：在中国，如何实现全部使用VPN，而不分流？哪怕访问百度，也就是让全部流量走VPN？
> 
> 我已经把能删除的分流规则全部删除，但仍然有geosite、Geoip是无法删除、或选择也让它们走VPN通道：
> 
> <img alt="Screen Shot 2024-11-21 at 01 10 32" width="391" src="https://private-user-images.githubusercontent.com/15896194/388196689-66661879-9ec1-4024-8f04-b10ffff12d4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNTIyMzgsIm5iZiI6MTczMjE1MTkzOCwicGF0aCI6Ii8xNTg5NjE5NC8zODgxOTY2ODktNjY2NjE4NzktOWVjMS00MDI0LThmMDQtYjEwZmZmZjEyZDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDAxMTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNjAzOGRhY2YzZWY0MjYyYzg4ZGE5ZDE4OGYwOTUwYzgzOWVhZDZjZWY1MDc4OGQwNGQ2Mzk4ZDU3Y2NkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0lBys9ux6BnhhPJPSygMQdKdOq4J7xMZEdzcippZJic">
> 所以，请问如何彻底禁止分流？或将geosite、Geoip也设置为VPN代理？
> 
> 多谢了

多使用 网络检测 排查问题
geosite, geoip 有分流里有开关,自己找找
