### ISSUE TITLE
win版客户端更新最新版本后，某些软件翻墙出问题

### ISSUE THREAD

**Issue by hugege88** [KaringX/karing#468]
![无标题](https://github.com/user-attachments/assets/295e81a1-5529-4844-8722-17c05ed72af7)

1  win版客户端更新最新版本后，用全局代理+TUN，无法带起 WhatsApp，提示没有网络连接。用karing老版本没问题，但是老版本我已经删除了，不知道是哪个版本了。

2  win版客户端更新最新版本后，用全局代理+TUN，微信登录不了。提示无网络连接。用 karing老版本无问题。

3 我换成flclash翻墙，用同样的机场线路，开规则模式+系统代理+TUN模式，无任何问题。如下图。

![QQ图片20241121191603](https://github.com/user-attachments/assets/0e907f8a-abaa-4654-affa-1ca2fcb145e3)

**请开发者尽快修复这个问题，非常感谢，就算捐款赞助，我也愿意，因为这个软件，的确很好用。**

**Comment by hugege88** [comment]
再次反馈：以上2个问题，有时候不会出现；但是有时候又会出现。不稳定。

请开发者解决这个不稳定的问题。

**Comment by GooRingX** [comment]
1. 出现问题先到 常见问题或者使用教程
2. 网络检测 和 连接状态 能找到大部分问题的原因
3. 看现象大概率是dns有问题,看看教程
