### ISSUE TITLE
增加设置指定域名查询 DNS 服务器的功能

### ISSUE THREAD

**Issue by vitaminc55** [KaringX/karing#472]
想要某个域名，或者一些域名使用特定的 DNS 服务器解析，例如，微软的域名使用 DNS 服务器 4.2.2.1 来解析。目前好像无法实现这个功能。

**Comment by alexlii1971** [comment]
嗯，这是个不错的Feature request

**Comment by GooRingX** [comment]
启用 dns分流规则

**Comment by vitaminc55** [comment]
> 启用 dns分流规则- 启用后,dns的查询会根据分流设置选择对应的dns服务器解析

这个只能自定义代理和直连的 DNS 解析，想要更细致化的自定义特定域名的 DNS 解析服务器就没办法，类似于 clash meta 的 nameserver-policy 功能
![IMG_20241125_130429](https://github.com/user-attachments/assets/15e833a7-0656-41cc-a4ac-1bbc0cb7e3d5)
