### ISSUE TITLE
有两个分流设置，请问分流设置以那个为准？

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing#473]
您好，请看：

<img width="402" alt="Screen Shot 2024-11-24 at 19 46 40" src="https://github.com/user-attachments/assets/088ec2cd-f5c1-4e73-9dbd-f62740eb6679">

同时在分流规则中有个：“禁用ISP分流规则”

<img width="400" alt="Screen Shot 2024-11-24 at 19 48 34" src="https://github.com/user-attachments/assets/a356e465-c2ae-4b24-a4bc-1f5601c067ab">

请问以那个为准？是否应该只设置一个？
如果二者有区别，请问区别是什么？或是否添加一点说明文字，解释二者区别？

谢谢

**Comment by GooRingX** [comment]
dns分流是根据分流规则,让dns也选择对应的dns服务器解析
isp分流规则是你vpn 机场提供的规则
