### ISSUE TITLE
请允许自定义：“分流”-- Rule set--下三项设置

### ISSUE THREAD

**Issue by alexlii1971** [KaringX/karing#474]
您好，

Rule set下 三项设置：

Geosite
Geoip
ACL

如果它们被启用，那么默认都是CN，它好像跟随“分流”中的“国家与地区”中的国家， 且无法修改。

在很多情况，我们需要仍然使用VPN访问本地资源。不知道，允许它们自定义的话，是否可以实现VPN访问本地资源的目的？？

如果可以，请允许修改为自定义通过代理。

或者，设置一个一键按钮实现全部通过VPN来访问互联网资源，比如允许在““国家与地区”不选择默认国家来实现？

谢谢

**Comment by GooRingX** [comment]
禁用后到自定义里自行添加
