### ISSUE TITLE
安卓平台连接wifi无法使用，必须要关闭wifi使用流量，才可以显示vpn图标正常使用

### ISSUE THREAD

**Issue by biannnnnnn** [KaringX/karing#475]

**Comment by biannnnnnn** [comment]
[图片][图片][图片]

**Comment by biannnnnnn** [comment]
![Uploading 6fb6a0bba9d38b7d4767788d1127cc1.jpg…]()
![Uploading 7f1a9012c2cc75f46a38a843d0f15d1.jpg…]()
![Uploading c81f35ef18844aacd9b028350a69fc8.jpg…]()

**Comment by GooRingX** [comment]
按照使用教程及faq排查过后,再反馈问题
