### ISSUE TITLE
[建议]能否去掉"karing.app"的默认直连

### ISSUE THREAD

**Issue by jia-cheng-zhao** [KaringX/karing#476]
![Screenshot_2024-11-25-12-54-48-991_com.android.chrome.jpg](https://github.com/user-attachments/assets/a61471bc-3f22-4fc3-9d69-fade7a43e4aa)

![Screenshot_2024-11-25-12-51-51-956_com.nebula.karing.jpg](https://github.com/user-attachments/assets/1b81977f-e1db-4e44-87d5-88ea5f2758ee)

本地ISP已无法直连访问，并且自定义分流规则无法覆盖`karing.app`域名的分流。

希望可通过自定义规则覆盖。

**Comment by GooRingX** [comment]
开启全局模式访问
