### ISSUE TITLE
建议重新审查一下Karing的DNS服务器列表

### ISSUE THREAD

**Issue by taoqixfz** [KaringX/karing#479]
最近迷恋上用quic协议和h3协议的DNS，无意间发现软件自带的DNS服务器列表内有不正确的DNS地址
![1](https://github.com/user-attachments/assets/724b2ce6-d46a-4a38-99c4-89e60a0dc800)
![2](https://github.com/user-attachments/assets/2236b7aa-77eb-4e58-aff7-cd493812390d)
https://adguard-dns.io/kb/zh-CN/general/dns-providers/

**Comment by GooRingX** [comment]
此dns没有问题.没有在列表里不代表不对.延迟测试一下就能发现
