### ISSUE TITLE
请求添加选项：仅ipv4 入站

### ISSUE THREAD

**Issue by heywood2988** [KaringX/karing#480]
请求添加选项：仅ipv4 入站，用于解决一些问题 https://github.com/SagerNet/sing-box/issues/1410
目前是双栈且不可更改。（现有那个是更改 ipv6 路由
![IMG_20241204_140904.jpg](https://github.com/user-attachments/assets/f5ac2a08-8943-45d8-b2fd-5dd14dcc9983)

**Comment by GooRingX** [comment]
设置-禁用ipv6
