### ISSUE TITLE
Problem with .exe in routing rules.

### ISSUE THREAD

**Issue by MaxKkk345** [KaringX/karing#486]
Here's my problem: in the latest versions, I can't enter the Discord voice channel. The app itself opens, but there are still problems accessing the voice channel. Discord.exe is proxied, but not completely. I mean that when I enter the voice channel, the Discord IP address (66.22.237.27) appears in the connections, but for some reason it is not connected to Discord.exe, although it should be. Due to the fact that it is not connected to Discord.exe, the connection goes directly through "finals" and I hang at the moment of "connecting to RTC".
I want to note that in version .459 I do not observe this problem, and Discord.exe is completely proxied. It goes throught personal rule over the current server and I can join voice channel.

In my routing rules, only Discord.exe is specified

Why does this IP address appear? Is this a bug or can I fix it myself? Please help.
![image](https://github.com/user-attachments/assets/53118b2e-c960-4aa2-8d76-6514f0d6f71d)
![image](https://github.com/user-attachments/assets/3759485b-f7c3-4e77-9553-e667fca76cc5)

**Comment by MaxKkk345** [comment]
![image](https://github.com/user-attachments/assets/102a4176-27d0-4623-8506-a73c3d499b06)
This is on version .459. Everything works fine

**Comment by GooRingX** [comment]
Use the latest version, go to Settings-About-Developer Tools-Open File Directory, clear the service_core.log file content, open the debug log; reopen the connection, and upload the service_core.log content; also use tcpview.exe in the attachment to view the process name corresponding to the port after the second line(10.21.0.1:56567 -> port 56567) to see if it is Discord.exe
[tcpview64.zip](https://github.com/user-attachments/files/18120702/tcpview64.zip)

**Comment by GooRingX** [comment]
I tested and found that Discord.exe is identifiable. If Discord.exe is not identifiable, it will cause a diversion error.

**Comment by MaxKkk345** [comment]
> I tested and found that Discord.exe is identifiable. If Discord.exe is not identifiable, it will cause a diversion error.
[service_core.log](https://github.com/user-attachments/files/18120854/service_core.log)
![image](https://github.com/user-attachments/assets/b5f5bdae-76b0-4753-a83a-c4872277f682)
![image](https://github.com/user-attachments/assets/0d6c9e99-c5bc-4006-afe1-2176e72a2786)

**Comment by DmitriyFrogo** [comment]
I thought it was Karing issue by design, but you say there's no issue in .459 - than it's probably bug in newer versions
Also, if you disable TUN and enable System Proxy, voice server subnets goes within Discord.exe, but when you use TUN - this subnets goes outside Discord.exe when you see Connections UI

> can I fix it myself
Yes, just temporary add IP/Cidr rule
66.22.237.0/24

Also we know that Discord using port range from 50000 to 65535 for voice connections, so I can suggest developer to add the ability to add port ranges, like 50000-65535 (or 50000:65535), which would also help us bypass this problem
Because we can't do it right now in Karing - only one port per line allowed

**Comment by MaxKkk345** [comment]
> Yes, just temporary add IP/Cidr rule
> 66.22.237.0/24

Tried but it doesn't help.

I see this when I join voice channel
![image](https://github.com/user-attachments/assets/e4161e87-64af-4cb5-a897-5d6e2811f1a5)

**Comment by GooRingX** [comment]
Confirm whether the latest version can identify the Discord.exe process? Only by identifying it can the process name-based diversion be used correctly

**Comment by DmitriyFrogo** [comment]
> Confirm whether the latest version can identify the Discord.exe process? Only by identifying it can the process name-based diversion be used correctly

Nope, still the same
It can identify Discord.exe, but not voice server connections
![discord](https://github.com/user-attachments/assets/f2f22fb6-0a91-4dd2-ac83-559ee3f0a6c4)

**Comment by MaxKkk345** [comment]
![image](https://github.com/user-attachments/assets/54de74ef-cab8-4b2f-9be2-9205d083dc1e)
Added this and joined

**Comment by GooRingX** [comment]
> ![image](https://private-user-images.githubusercontent.com/191498325/395506981-54de74ef-cab8-4b2f-9be2-9205d083dc1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODI2MjYsIm5iZiI6MTczNDA4MjMyNiwicGF0aCI6Ii8xOTE0OTgzMjUvMzk1NTA2OTgxLTU0ZGU3NGVmLWNhYjgtNGIyZi05YmUyLTkyMDVkMDgzZGMxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwOTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDc5OGZjNTIzMDY3ZTQxNzgyYmJlMGRjYTZlZDRjNzhjZDc1OTA5ZmExOWRmN2E3NDczM2NlZDgwN2E1NGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uOAgOKT3k76OEjl-ur1uwfDuhRjWVlYJ44IshlJsoXM) Added this and joined
Which process is port 61133?

**Comment by MaxKkk345** [comment]
> > ![image](https://private-user-images.githubusercontent.com/191498325/395506981-54de74ef-cab8-4b2f-9be2-9205d083dc1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODI2MjYsIm5iZiI6MTczNDA4MjMyNiwicGF0aCI6Ii8xOTE0OTgzMjUvMzk1NTA2OTgxLTU0ZGU3NGVmLWNhYjgtNGIyZi05YmUyLTkyMDVkMDgzZGMxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QwOTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDc5OGZjNTIzMDY3ZTQxNzgyYmJlMGRjYTZlZDRjNzhjZDc1OTA5ZmExOWRmN2E3NDczM2NlZDgwN2E1NGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uOAgOKT3k76OEjl-ur1uwfDuhRjWVlYJ44IshlJsoXM) Added this and joined
> > Which process is port 61133?

I can't find it in TCPView
![image](https://github.com/user-attachments/assets/ad7f7f07-d289-4232-ae65-51dc82df73ac)

**Comment by GooRingX** [comment]
If it is not found, it means that the request is not initiated by Discord.exe, so it will not hit the rule. Can you try to find out which version this problem occurs from?

**Comment by MaxKkk345** [comment]
> If it is not found, it means that the request is not initiated by Discord.exe, so it will not hit the rule. Can you try to find out which version this problem occurs from?

Ok I will

**Comment by MaxKkk345** [comment]
> If it is not found, it means that the request is not initiated by Discord.exe, so it will not hit the rule. Can you try to find out which version this problem occurs from?

I tried versions 460-465.
Problem starts in version 462. In 461 everything works fine.
Also in version 464 I've got a trojan (Kaspersky detected)

**Comment by minecraftpornomafia** [comment]
Can confirm that .exe routing doesn't work on latest stable and pre-release builds. It works on stable 1.34. Probably newest versions have problems with identifying UPD connections coming from executable files.

**Comment by GooRingX** [comment]
Install https://github.com/KaringX/karing/releases/tag/v1.0.37.486, use the karingService.exe in the attachment below to replace the installed version of karingService.exe and test
[karingService.zip](https://github.com/user-attachments/files/18144025/karingService.zip)

**Comment by MaxKkk345** [comment]
> Install https://github.com/KaringX/karing/releases/tag/v1.0.37.486, use the karingService.exe in the attachment below to replace the installed version of karingService.exe and test [karingService.zip](https://github.com/user-attachments/files/18144025/karingService.zip)

Erething works fine. Thank you so much!

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.37.487
