### ISSUE TITLE
Can't add new lines in diversion rules

### ISSUE THREAD

**Issue by DmitriyFrogo** [KaringX/karing#487]
Can't add new lines when editing diversion rules with pressing Enter
OS: Windows

Last good known version than I can test - v1.0.36.475
First bad known that I can test - v1.0.37.482

Example videos:
<details>
<summary>v1.0.36.475</summary>

https://github.com/user-attachments/assets/45646bf0-0917-4a46-a21b-6901737e88e4
</details>
<details>
<summary>v1.0.37.482</summary>

https://github.com/user-attachments/assets/e03adad5-9039-4bec-a5c6-20f74cbb8c9d
</details>

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.37.486
