### ISSUE TITLE
TUN mode共享上网 问题

### ISSUE THREAD

**Issue by jerry001-free** [KaringX/karing#493]
win10系统我测试了一下 
我的笔记本插上了网线上网 我在karing启用了TUN mode共享上网
此时生成了karing TUN的虚拟网卡
然后我通过笔记本开启了wifi热点 
这时也生成了一个热点用的虚拟网卡 
此时，我把karing TUN虚拟网卡共享了给无线热点的虚拟网卡 
理论上其它连上笔记本的热点的设备测速都能科学上网了对吧？
但是 现在是手机和PAD 都不能上网，无法联网。。。。
但是我前两天是可以成功使用并上 外网的，不知道是什么原因 ？
版本号1.0.36.475

**Comment by GooRingX** [comment]
此功能有系统提供,请自行搜索
