### ISSUE TITLE
iOS to disable VPN in sleep mode (screen lock)

### ISSUE THREAD

**Issue by ElonJunior** [KaringX/karing#494]
## desc
- platform: ios
- requirement：disable VPN in sleep mode (screen lock)

![image](https://github.com/user-attachments/assets/75eacc11-4b79-4531-91d3-c33042a9bcf8)

![image](https://github.com/user-attachments/assets/c8298a46-af76-4c57-a1a5-9776ee673d5c)

## questioner
form @mrmax380：
Will a feature be added to iOS to disable VPN in sleep mode (screen lock)?
Introducing this feature would really help save battery life. I really want to use your app, but on iOS, it drains the battery twice as fast as V2BOX with its power-saving mode.

**Comment by GooRingX** [comment]
stop(pause) on sleep is the default setting and does not require manual setting by the user
