### ISSUE TITLE
UDP connections

### ISSUE THREAD

**Issue by DikozImpact** [KaringX/karing#495]
On Windows udp connections do not have application/domain IDs. Now on windows it is almost impossible to set up normal routing, as each udp connection has to be added independently, when some applications have hundreds of different udp connections. There is no such problem in Android. 1 screenshot - Windows. 2 screenshot - Android 
![image](https://github.com/user-attachments/assets/1fd4c6bf-080c-40bf-a7ac-d17bfd9c290f)
![image](https://github.com/user-attachments/assets/1bf8e090-1366-457c-a419-fefcd0a84cf2)

**Comment by GooRingX** [comment]
No karing version number provided

**Comment by DikozImpact** [comment]
> No karing version number provided, Also refer to https://github.com/KaringX/karing/releases/tag/v1.0.37.487 update log

I used the latest release. Just checked the beta and in it UDP connections have process IDs. Sorry for wasting your time. I'm sorry I didn't check the beta version first
