### ISSUE TITLE
一些想法

### ISSUE THREAD

**Issue by fllesser** [KaringX/karing#500]
1.自动选择和自定义代理组能否添加显示在主界面(个人感觉这样更清晰，方便切换下载节点)
2.自定义代理组能否支持 fallback 
3.个人感觉按钮可以不用设计这么大，顺便可以腾一点空间给建议1

**Comment by GooRingX** [comment]
1. 不会
2. 内核不支持,目前尚未无计划支持
3. 等ui改版
