### ISSUE TITLE
Application crash on Windows

### ISSUE THREAD

**Issue by HarwoodKinnav** [KaringX/karing#51]
When you launch an application, a window appears for a few seconds, after which the application closes.
The latest working version is v1.0.0-16
I believe this is due to the old processor without support sse4.1 and Flutter 3.16.0 (Dart 3.2.0)
As far as I understand, this problem was fixed in Flutter 3.19.5 (Dart 3.3.3)
Is it possible to fix this problem in the program?

**Comment by GooRingX** [comment]
os version?

**Comment by HarwoodKinnav** [comment]
> os version?

Windows 11 23H2 build 22631.3527

**Comment by GooRingX** [comment]
In the next version(1.0.21.xxx) we will update from 3.19.2 to 3.19.6

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.21-230
