### ISSUE TITLE
Internet Access Blocked for Other Apps except Telegram, While Using Karing (v1.0.19.207 & v1.0.20)

### ISSUE THREAD

**Issue by MEHR1DAD** [KaringX/karing#52]
## Description:

The Karing app (versions 1.0.19.207 from App Store and 1.0.20 from TestFlight) completely blocks internet access for all apps except Telegram on the latest iOS version.

**Steps to Reproduce:**

1. Launch the Karing app.
2. Open any other app requiring internet access (e.g., Speedtest, Twitter, YouTube).
3. Notice that all affected apps are unable to connect to the internet.

**Expected Behavior:**

Other apps should be able to access the internet simultaneously while Karing is running.

**Actual Behavior:**

Only Telegram maintains internet connectivity, while all other apps are completely blocked.

**Additional Information:**

- This issue does not occur with other similar VPN apps like Shadowrocket, Stash, and Streisand, which work well with the same configuration on the same Wi-Fi network.
- Troubleshooting steps like restarting the phone and reinstalling Karing haven't resolved the problem.

**Device Information:**

- Device: iPhone 14
- iOS Version: 17.4.1

**Request:**

This critical issue requires immediate attention. Karing's current behavior prevents internet access for essential apps, except Telegram. A fix is necessary to ensure other apps function normally alongside Karing.

**Comment by GooRingX** [comment]
sounds like dns setting issue(telegram use ip), dns->final->test dns,then set dns by check result, as well as other dns options

**Comment by MEHR1DAD** [comment]
Absolutely! Thanks for your help in diagnosing the issue.  Following your suggestion to check the DNS settings and test different options seems to have resolved the problem. I can now access the internet with other apps while using Karing.  I appreciate your quick response and guidance!
