### ISSUE TITLE
Add Fragment option

### ISSUE THREAD

**Issue by emad465** [KaringX/karing#54]
Please add **fragmentation** option to the karing app. fragmentation for Iran is a **necessary** option , many configs dosen't work without that. For more information please read **V2rayN** github  or **Hiddify next** github .
v2rayn git : **https://github.com/2dust/v2rayN**
hiddify next git : **https://github.com/hiddify/hiddify-next**
Thanks karing team.

**Comment by ahmad660a** [comment]
Please add fragmentation option to the karing app. fragment option in Iran is a necessary option , many configs dosen't work without that. 
Thanks

**Comment by GooRingX** [comment]
Join https://t.me/KaringApp and provide the admin GooRingX vowe with the test subscription link

**Comment by GooRingX** [comment]
try https://github.com/KaringX/karing/releases/tag/v1.0.22-242
