### ISSUE TITLE
Error on handshake

### ISSUE THREAD

**Issue by freedomOfIR** [KaringX/karing#56]
HI
Thanks for build this app
in my system don't work

This Error show but other app work correctly

**exception:HandshakeException: Connection terminated during handshake**

![2024-05-05_032034](https://github.com/KaringX/karing/assets/168939491/d98e51ae-5b58-45c5-a229-46841472c5a1)
![2024-05-05_031929](https://github.com/KaringX/karing/assets/168939491/16eccb82-70a7-4bed-803b-d130f2ca5a66)

**Comment by GooRingX** [comment]
try other proxy server

**Comment by alirezavafakhah** [comment]
the problem don't fix in lastest update

**Comment by GooRingX** [comment]
what is your final dns?

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.24-285
