### ISSUE TITLE
将配置文件保存在软件目录下

### ISSUE THREAD

**Issue by sdgsdsdhshd** [KaringX/karing#57]
使用启动参数的话，设置开机自启动他就会又去找系统目录了，而不是使用软件路径。可以将这作为一个选项，或者是像clash那样增加一个文件夹来识别吗

**Comment by GooRingX** [comment]
1.0.21.230 将改成在exe同目录创建 profiles 文件夹即可,命令行方式不再支持

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.21-230
