### ISSUE TITLE
代理集群和WS路径

### ISSUE THREAD

**Issue by Neomanbeta** [KaringX/karing#6]
请教一下，浏览了一下快速入门没有找到解释的地方。
1：“开启socks/http代理集群”，这个选项的作用是什么呢？类似负载均衡？
2：如果WS的path是/example?ed=2048这种格式，导入以后节点是不工作的，必须改path为/example，然后写earlydata name为Sec-WebSocket-Protocol和earlydata length为2048才工作，希望后续版本能支持?ed=2048这种写法。

**Comment by KaringX** [comment]
1. 代理集群:将订阅的代理列表批量转换成本地socks/http代理服务器
2. bug, 50版本修复

**Comment by Neomanbeta** [comment]
多谢解释，那我理解就是，如果我的订阅里有10个节点，那么我打开了这个选项，我的系统上就会同时连接这10个节点，并生成10个socks以供我使用？
如果我并不用订阅，都是手动导入的节点，那么这个选项开不开对我来说都没有意义？

**Comment by KaringX** [comment]
订阅和导入效果一样
点击 允许其他主机接入代理集群 左侧 信息按钮, 用浏览器打开 提示中的url, 可以看到可用的代理信息

**Comment by Neomanbeta** [comment]
OK，现在明白了。
