### ISSUE TITLE
win版本开启tun模式能加到主页吗

### ISSUE THREAD

**Issue by sdgsdsdhshd** [KaringX/karing#60]
一般给一些不走代理的软件时候才开tun模式。而tun开启在设置里，每次开启比较麻烦，能把开启开关加到系统代理下面吗，方便切换

**Comment by GooRingX** [comment]
低频操作不会放到主屏
tun不需要每次开启，开启后，如果以管理员身份启动，就会使用tun，否则使用系统代理
