### ISSUE TITLE
karing.log file size issue in version Karing 1.0.21.231

### ISSUE THREAD

**Issue by zerolcc** [KaringX/karing#61]
Description:
I encountered an issue with the karing.log file consuming an unusually high amount of disk space, reaching up to 146GB. I did not have any proxies enabled on my end, just some configurations added. The backend was set to refresh configurations every minute, and suddenly one morning, this led to the karing.log file getting filled up rapidly.

Directory: C:\Users\x\AppData\Roaming\karing\karing\karing.log

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.21-236
