### ISSUE TITLE
Not work vless+tcp+http+heder config 

### ISSUE THREAD

**Issue by aliakbar123as** [KaringX/karing#62]
Hi
The biggest problem of this program is that it does not support this type of configuration or it has a bug Or it is broken because this type of configuration does not work at all in the program that is related to V2ray  LT is

Vlees tcp http hedear No matter how much we tested it, we received error 503 in the program and it has a problem like the picture below 
![Screenshot_2024-05-09-11-08-59-034_com nebula karing](https://github.com/KaringX/karing/assets/69392926/d9f3bbe7-13e8-4b3c-b647-51ce14f32505)
![IMG_20240509_104913_687](https://github.com/KaringX/karing/assets/69392926/7ecbc167-ffa3-4701-b5d6-8e299b887cac)
 
This is if we tested the configuration in other programs and it worked correctly and without problems like the program. V2RAYng  which was working without any problem, but not in this program, I am sending the configuration structure, maybe you solved this problem 

vless://f6e999f4-9941-4c24-9d5f-8b819709a9fa@red562.redocean99.xyz:5627?security=none&encryption=none&host=doi.org&headerType=http&type=tcp#test

**Comment by aliakbar123as** [comment]
Please fix this problem as soon as possible. How long will it take to fix this problem?

**Comment by GooRingX** [comment]
tested with v2rayN and Hiddify , all failed

**Comment by aliakbar123as** [comment]
I tested this protocol on both programs and it works well, but in this program, I noticed that the code that I saw was not added to the core, so it does not support this portkey. Why not add this item to the core?

**Comment by GooRingX** [comment]
what portkey?

**Comment by aliakbar123as** [comment]
I meant the protocol that this program does not support this type of configuration and you did not add this, but the program v2rayNG It supports this type of configuration. The meaning of the type of configuration is this type:

Vless tcp http hedear 
The program does not support this configuration model
