### ISSUE TITLE
安卓手机分应用代理不生效

### ISSUE THREAD

**Issue by STEVENTAN100** [KaringX/karing#64]
我把final设置为直连，勾选分应用代理白名单，但所有的网址都不走代理了，此外，知乎的分流总是有些问题

**Comment by STEVENTAN100** [comment]
知乎app一开vpn就提示“似乎有些问题”，别的国内应用尚未见此情况，就算是代理，怎么设置分流规则都没有用

**Comment by STEVENTAN100** [comment]
pre-release版本已修复，感谢作者大大的好应用

**Comment by xy3xy3** [comment]
我的知乎设置了直连也不行，是知乎主动检测吗
