### ISSUE TITLE
希望能够隐藏后台。

### ISSUE THREAD

**Issue by mccation** [KaringX/karing#65]
在控制中心里直接连接，不会进入软件。

**Comment by STEVENTAN100** [comment]
什么意思？Windows上关闭就是隐藏到小图标了

**Comment by GooRingX** [comment]
android版本依赖前台程序实现一些功能,因为无法实现纯后台

**Comment by waoui** [comment]
在控制中心连接的时候，有时候点击之后会跳转到应用界面，显示一遍启用代理的界面操作，这个算bug吗，希望可以在控制栏做到无感启动

**Comment by GooRingX** [comment]
> 在控制中心连接的时候，有时候点击之后会跳转到应用界面，显示一遍启用代理的界面操作，这个算bug吗，希望可以在控制栏做到无感启动

不是bug.24小时内必须激活一次
