### ISSUE TITLE
iOS版本1.0.4.58无法连接

### ISSUE THREAD

**Issue by zptan** [KaringX/karing#7]
如题，最新版本无法使用

![image](https://github.com/KaringX/karing/assets/17807777/e611517f-f127-47f7-a715-f8d6b1359116)

点击OK后，点击按钮后显示连接成功，但是打开其他app后按钮自动变为非连接状态，还是不能用

iOS: 16.1.1
Karing: 1.0.4.58

**Comment by KaringX** [comment]
问题已修复,等1.0.5.67发布后更新, 更新后需要重新添加配置或手动更新配置
