### ISSUE TITLE
Add Support for Android TV

### ISSUE THREAD

**Issue by MEHR1DAD** [KaringX/karing#71]
I'd like to request the addition of Android TV support for Karing. While Karing offers a great user experience on mobile devices, extending its functionality to Android TV would be a welcome improvement.

**Benefits of Android TV Support:**

* **Enhanced Streaming Experience:** Karing's proxy capabilities could be leveraged to improve streaming experiences on Android TVs. Users could potentially bypass geo-restrictions and access a wider range of content on streaming platforms.
* **Improved Privacy on Smart TVs:**  With growing concerns about smart TV data collection, Karing's proxy functionality could offer users more control over their privacy while using their Android TVs.
* **Expanding Karing's User Base:**  Supporting Android TV would open Karing up to a new user base who primarily consume content on their televisions.

**Technical Considerations:**

* **User Interface:**  A user-friendly interface optimized for navigation with a remote control would be essential for a smooth experience on Android TV.
* **Remote Control Compatibility:**  Karing's Android TV app should be compatible with various remote controls used with different Android TV devices.
* **Integration with Existing Features:**  Existing Karing features like proxy selection and connection management should be seamlessly integrated into the Android TV app.

**Request:**

I kindly request the Karing developers to consider adding support for Android TV. This would allow users to enjoy the benefits of Karing's proxy functionality on their televisions, expanding its reach and providing a valuable tool for streamers and privacy-conscious users.

Thank you for your time and consideration.

**Comment by kai2ou** [comment]
Good idea

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27-330

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.27-331

**Comment by GooRingX** [comment]
#189
