### ISSUE TITLE
The node speed of the Wireguard protocol is slower than that of Calsh Meta

### ISSUE THREAD

**Issue by Zhizhr** [KaringX/karing#73]
Nodes made with warp are slower in Karing than Clash Meta.
![calsh meta - 副本](https://github.com/KaringX/karing/assets/97087300/95833370-3f7e-4e68-afc3-c5e38b737967)
![karing - 副本](https://github.com/KaringX/karing/assets/97087300/7ccec4cd-533f-4911-9402-131f1b831f3b)

**Comment by GooRingX** [comment]
请提供测试用数据

**Comment by GooRingX** [comment]
dns- 禁用 [final]通过代理服务器解析dns后数据相差不大,另外延迟不完全代表使用使用体验. 机场配置和karing配置区别大, 可能会出现数据上有较大差异,正常现象
