### ISSUE TITLE
自动选择有问题！

### ISSUE THREAD

**Issue by abbaababa** [KaringX/karing#75]
当你指定App 连接一个节点后，并在分流规则里设置了某个App 连接自动选择节点，再开启karing 的VPN，不会自动测速，刚才设置的分流规则，自动选择不起作用！

**Comment by GooRingX** [comment]
如果当前选择不是自动选择, 则不会自动测试延迟.

**Comment by abbaababa** [comment]
@GooRingX 问题在于，在分流规则里，设置了某个规则走自动选择节点，也不发挥作用，那不正常，也不合理！
