### ISSUE TITLE
[BUG]iOS 1.0.5.68 客户端

### ISSUE THREAD

**Issue by Neomanbeta** [KaringX/karing#8]
节点地址为ipv6的时候会无法连接，以前的版本没有这个问题，删除了重新添加也不行。
win客户端没有这个问题。

**Comment by KaringX** [comment]
请到电报群联系管理员提供配置文件信息

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Neomanbeta ***@***.***>
发送时间: Thursday, January 11, 2024 4:58:34 PM
收件人: KaringX/karing ***@***.***>
抄送: Subscribed ***@***.***>
主题: [KaringX/karing] [BUG]iOS 1.0.5.68 客户端 (Issue #8)


节点地址为ipv6的时候会无法连接，以前的版本没有这个问题，删除了重新添加也不行。
win客户端没有这个问题。

―

**Comment by Neomanbeta** [comment]
已解决。
