### ISSUE TITLE
自动选择有问题！？

### ISSUE THREAD

**Issue by abbaababa** [KaringX/karing#82]
自动选择不起作用！或者不显示自动选择的节点！已经开启了VPN 
![Screenshot_20240517_190434](https://github.com/KaringX/karing/assets/129253712/4c29076d-0035-4054-ad82-ab89c7fa4031)
![Screenshot_20240517_190506](https://github.com/KaringX/karing/assets/129253712/3269f539-a6ff-40f9-91ae-f70a6b69b247)

**Comment by GooRingX** [comment]
yacd为外部功能
