### ISSUE TITLE
Android客户端1.0.21无法导入配置文件

### ISSUE THREAD

**Issue by joescon** [KaringX/karing#83]
你好，感谢开发Karing。

安卓客户端1.0.21，Redmi Note 12 Turbo，HyperOS 1.02.0版本软件下，无法导入.yaml后缀的配置文件。
具体情况是，在Karing Android客户端导入配置文件，找到配置文件后，无法选中，无法导入。

同一个yaml配置文件，在Karing iOS客户端可以正常使用。
麻烦看下是什么问题，感谢。

**Comment by GooRingX** [comment]
文件发一下

**Comment by sdgsgsdf** [comment]
同样问题，文件直接是灰色的，然后不只是yaml格式，是任何格式的文件都是如此
![图片](https://github.com/KaringX/karing/assets/153086038/f1b4d567-0ff5-4111-bb87-848e39ebfd80)

**Comment by shykt235** [comment]
我也有一样的问题，任何格式的文件都是灰色，无法选中无法更改，以为是权限问题，但是看读取文件的那部分权限正常

**Comment by GooRingX** [comment]
fixed in 1.0.22.248
