### ISSUE TITLE
Geosite

### ISSUE THREAD

**Issue by Pedro-e** [KaringX/karing#85]
Please add Iran Geosite support thank you very much

**Comment by GooRingX** [comment]
fixed in 1.0.22.246

**Comment by GooRingX** [comment]
Please provide data source

**Comment by Pedro-e** [comment]
> Please provide data source

https://github.com/Chocolate4U/Iran-v2ray-rules

**Comment by GooRingX** [comment]
ruleset format supported only

**Comment by GooRingX** [comment]
https://github.com/Chocolate4U/Iran-sing-box-rules/tree/main

**Comment by GooRingX** [comment]
[geoip-ir.srs](https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geoip-ir.srs) It has been built into karing, geosite currently needs to be added manually, and ir geosite[https://raw.githubusercontent.com/Chocolate4U/Iran-sing-box-rules/rule-set/geosite-ir.srs] will be built into subsequent versions.

**Comment by GooRingX** [comment]
geosite for ir : 1.0.22.248
