### ISSUE TITLE
More Advanced TLS Fragment setting

### ISSUE THREAD

**Issue by Economic-PunPun** [KaringX/karing#94]
Hi,
Can you provide Advanced Fragment settings?
- set a range for Fragment Size and Delay like 5-10
- an option to choose fragmented packets instead of just tlshello. like 1-2

**Comment by GooRingX** [comment]
set a range for Fragment Size and Delay like 5-10---
settings-tls

**Comment by Economic-PunPun** [comment]
Windows App Does not allow to set a range for fragment like this in hiddify next:
![image](https://github.com/KaringX/karing/assets/109609472/d70558d1-d445-42e2-8c40-8a2e2e9dafb3)
it just allow setting a single number
![image](https://github.com/KaringX/karing/assets/109609472/436cd2bd-369a-4f1d-a364-f905e8edc9b4)


and recently Iran firewall could block tlshello fragment. Can you provide An option to set fragmented packets like this xray config?
"fragment": {
          "packets": "1-2",
          "length": "25-30",
          "interval": "100-150"
        }

**Comment by GooRingX** [comment]
Thanks , will support in 1.0.23.260

**Comment by Economic-PunPun** [comment]
appreciate it.
