### ISSUE TITLE
❤️❤️Add futures Warp❤️❤️

### ISSUE THREAD

**Issue by moli1369** [KaringX/karing#97]
Please add Future Warp+.
in such a way that it uses the hiddify input panel.
Also add new protocols.

**Comment by misagh72** [comment]
1: you add warp like this
warp://ip:port
2: which protocols do you mean

**Comment by moli1369** [comment]
I have a Warp license in my panel and I only activate it in the Hidify program and it uses my license which is in the user panel of the subscribers and thus avoids showing my original IP.
Thank you for activating this plugin so that by activating Warp in your good program, it can use the license panel of the user or client, that is, it is a way to share Warp account and pass my traffic through Warp.

**Comment by moli1369** [comment]
https://github.com/search?q=repo%3Ahiddify%2FHiddify-Manager+warp&type=code&p=2

**Comment by moli1369** [comment]
protocols
Delicately-TUICed
Hysteria 
REALITY 
WireGuard 
Shadowsocks 
TLS:https://hiddify.com/manager/basic-concepts-and-troubleshooting/How-the-TLS-Trick-works-and-its-usage/
MUX==Multiplex-sMux-YaMux-h۲Mux
MUX Padding
 MUX Brutal 
SSH 
Trojan
VLess
TCP
Enable QUIC Protocol
XTLS
h2
HTTPUpgrade
gRPC
Websocket
VMess

**Comment by moli1369** [comment]
In which part of the program should I add and confirm the warp?

**Comment by misagh72** [comment]
> protocols Delicately-TUICed Hysteria REALITY WireGuard Shadowsocks TLS:https://hiddify.com/manager/basic-concepts-and-troubleshooting/How-the-TLS-Trick-works-and-its-usage/ MUX==Multiplex-sMux-YaMux-h۲Mux MUX Padding MUX Brutal SSH Trojan VLess TCP Enable QUIC Protocol XTLS h2 HTTPUpgrade gRPC Websocket VMess

all protocol supported except for muxing

**Comment by misagh72** [comment]
> In which part of the program should I add and confirm the warp?

import from clipboard

**Comment by MEHR1DAD** [comment]
## Inquiry Regarding Karing's Warp Support Functionality

**Title:** Clarification on Karing's Warp Connection Support

**Description:**

I'm writing to follow up on the recent update that introduced Warp connection support in Karing. I'm excited about this new functionality and would appreciate some clarification on its capabilities.

In a [previous](https://github.com/KaringX/karing/issues/55#issuecomment-2106677565) issue request on GitHub, I mentioned various Warp connection formats supported by Hiddify, another proxy client. These formats included:

* `warp://engage.cloudflareclient.com:2408/` (Basic Warp connection)
* `warp://engage.cloudflareclient.com:2408/?ifp=5-10` (With Fragment for SNI hiding)
* `warp://zula.ir:2408/?ifp=5-10` (Using a custom domain with Cloudflare CDN)
* `warp://license@engage.cloudflareclient.com:2408/?ifp=5-10` (Using a Cloudflare Warp license)
* `warp://auto` (Automatic discovery of the best Cloudflare IP/domain)

**Question:**

Could you please clarify which of these Warp connection formats are currently supported by Karing in its new update?

* Does Karing support basic Warp connections like `warp://engage.cloudflareclient.com:2408/`?
* Is SNI hiding functionality available through Warp connections in Karing, similar to `warp://engage.cloudflareclient.com:2408/?ifp=5-10` format?
* Can Karing utilize custom domains with Cloudflare CDN for Warp connections, as demonstrated by `warp://zula.ir:2408/?ifp=5-10`?
* Does Karing allow users to implement Cloudflare Warp licenses through a format like `warp://license@engage.cloudflareclient.com:2408/?ifp=5-10`?
* Is there an automatic discovery feature for the best Cloudflare IP/domain similar to `warp://auto` in Hiddify?

Understanding the specific Warp connection formats supported by Karing would be very helpful.

Thank you for your time and clarification.

**Comment by GooRingX** [comment]
warp://engage.cloudflareclient.com:2408/
warp://zula.ir:2408/
warp://auto
These formats are supported, ifp not supported yet

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.23-266  for ifp, ifps, ifpd

**Comment by GooRingX** [comment]
https://github.com/KaringX/karing/releases/tag/v1.0.23-267   detour , license
